export const channelPerformanceSnapshot = {
  collectedAt: "2026-07-02 22:45 KST",
  scope:
    "Public count snapshot. These numbers are channel/content signals, not product conversion, paid campaign, or commercial traction claims.",
  sourceSet:
    "TikTok public mirror API, IDOL repo social/web ledgers, YouTube public watch-page metadata, and yt-dlp public metadata.",
  heroStats: [
    { label: "TikTok recent-30 views", value: "9,097", detail: "@loom_mm public videos" },
    { label: "TikTok gender split", value: "not exposed", detail: "No admin analytics row in IDOL repo" },
    { label: "YouTube public views", value: "61", detail: "6 Loom/Pulso public videos" },
  ],
  platforms: [
    {
      platform: "TikTok",
      handle: "@loom_mm",
      url: "https://www.tiktok.com/@loom_mm",
      role: "Loom/Pulso short-form test channel",
      mainMetric: "9,097",
      mainLabel: "recent 30 public-video views",
      stats: [
        ["Followers", "29"],
        ["Total likes", "1,225"],
        ["Total videos", "206"],
        ["Recent 30 likes", "236"],
        ["Recent 30 saves", "30"],
        ["Recent 30 shares", "6"],
        ["Gender split", "not exposed"],
      ],
      note:
        "Best used as the main content-operation metric: many short clips, repeated AI idol hooks, and public short-form iteration. Gender split is not claimed because the public API and IDOL repo metric ledger do not expose a TikTok admin-audience snapshot.",
    },
    {
      platform: "YouTube",
      handle: "Loom/Pulso archive",
      url: "https://www.youtube.com/watch?v=DUyCAFHZ7X0",
      role: "Loom/Pulso/INK public video archive",
      mainMetric: "61",
      mainLabel: "public-video views",
      stats: [
        ["Public videos checked", "6"],
        ["Public likes", "1"],
        ["Top video views", "28"],
        ["Longest video", "2:44"],
        ["Comment count", "not exposed"],
        ["Channel role", "archive"],
      ],
      note:
        "Best used as supporting channel evidence, not the lead performance story. It shows owned video publishing coverage.",
    },
  ],
  contentCases: [
    {
      title: "Loom / Pulso short-form loop",
      target: "AI idol, K-pop, virtual idol, short-form viewers",
      intent: "Turn an AI idol IP into track, core video, TikTok clips, YouTube archive, and web proof surface.",
      role: "IP structure, track/member/video flow, AI production loop, publishing route, and channel evidence organization.",
      metrics: "TikTok recent 30: 9,097 views / 236 likes / 30 saves. Gender split: not exposed in public/IDOL ledger data. YouTube: 6 public videos / 61 views.",
    },
  ],
  tiktokVideos: [
    {
      date: "2026-06-24 19:14",
      title: "ink-yeul #grokai #aiidol #kpop #virtualidol #ink",
      url: "https://www.tiktok.com/@loom_mm/video/7654903404963122452",
      views: 934,
      likes: 18,
      comments: 0,
      shares: 0,
      saves: 3,
    },
    {
      date: "2026-06-24 01:14",
      title: "#kpop #aiidol #ai #virtualidol #loom",
      url: "https://www.tiktok.com/@loom_mm/video/7654624880796699924",
      views: 890,
      likes: 45,
      comments: 0,
      shares: 0,
      saves: 0,
    },
    {
      date: "2026-06-24 19:14",
      title: "ink-solo--rena#grokai #aiidol #kpop #virtualidol #ink",
      url: "https://www.tiktok.com/@loom_mm/video/7654903232178834709",
      views: 847,
      likes: 13,
      comments: 0,
      shares: 0,
      saves: 0,
    },
    {
      date: "2026-06-24 00:48",
      title: "#loom #kpop #virtualidol #ai #aiidol",
      url: "https://www.tiktok.com/@loom_mm/video/7654618213472505109",
      views: 844,
      likes: 16,
      comments: 0,
      shares: 5,
      saves: 5,
    },
    {
      date: "2026-06-24 19:15",
      title: "ink-solo#grokai #aiidol #kpop #virtualidol #ink",
      url: "https://www.tiktok.com/@loom_mm/video/7654903498840198420",
      views: 614,
      likes: 13,
      comments: 0,
      shares: 0,
      saves: 1,
    },
  ],
  youtubeVideos: [
    {
      date: "2026-05-29 23:58",
      title: "Loom Track 01 - Root Signal (Full Master)",
      url: "https://www.youtube.com/watch?v=DUyCAFHZ7X0",
      views: 28,
      likes: 1,
      duration: "2:44",
    },
    {
      date: "2026-06-17 20:16",
      title: "Pulso ✨ AURORA-M AI Idol",
      url: "https://www.youtube.com/watch?v=0vV4CXL3_Qk",
      views: 16,
      likes: 0,
      duration: "2:39",
    },
    {
      date: "2026-06-21 23:35",
      title: "Loom - Ink MV Edit Preview",
      url: "https://www.youtube.com/watch?v=HXNSMofX6mU",
      views: 9,
      likes: 0,
      duration: "46s",
    },
    {
      date: "2026-06-21 23:35",
      title: "Loom - Ink MV S04-S06 Preview v4",
      url: "https://www.youtube.com/watch?v=ft83ENFTiBw",
      views: 4,
      likes: 0,
      duration: "36s",
    },
    {
      date: "2026-05-09 07:00",
      title: "solana finality rail edit",
      url: "https://www.youtube.com/watch?v=IqJ4Ai1KoHo",
      views: 3,
      likes: 0,
      duration: "42s",
    },
    {
      date: "2026-05-09 13:15",
      title: "Hey grok",
      url: "https://www.youtube.com/watch?v=oxek8A9aits",
      views: 1,
      likes: 0,
      duration: "10s",
    },
  ],
} as const;
