export const channelPerformanceSnapshot = {
  collectedAt: "2026-07-02 22:45 KST",
  remeasuredAt: "2026-08-02",
  scope:
    "Public count snapshot. These numbers are channel/content signals, not product conversion, paid campaign, or commercial traction claims. Country, completion rate, average view duration, and audience age/gender are admin Analytics only and stay not exposed unless a Studio export is supplied.",
  sourceSet:
    "TikTok public metadata via yt-dlp (tiktokuser extract), YouTube public watch-page / Shorts metadata via yt-dlp. Older channel aggregates may retain the 2026-07-02 verification stamp.",
  heroStats: [
    { label: "TikTok recent-30 views", value: "9,097", detail: "@loom_mm · last verified 2026-07-02" },
    { label: "Audience country / completion", value: "not exposed", detail: "Admin Analytics only · public API none" },
    { label: "YouTube remeasure window", value: "5,679", detail: "Shorts+video views · 2026-07-03~ · measured 2026-08-02" },
  ],
  platforms: [
    {
      platform: "TikTok",
      handle: "@loom_mm",
      url: "https://www.tiktok.com/@loom_mm",
      role: "Loom/Pulso short-form test channel",
      mainMetric: "9,097",
      mainLabel: "recent 30 public-video views · last verified 2026-07-02",
      stats: [
        ["Followers", "29"],
        ["Total likes", "1,225"],
        ["Total videos", "206"],
        ["Recent 30 likes", "236"],
        ["Recent 30 saves", "30"],
        ["Recent 30 shares", "6"],
        ["Gender / age / country", "not exposed"],
        ["Completion / AVD", "not exposed"],
      ],
      note:
        "Main short-form operation surface. Gender, age, country, and completion are not claimed — public API and yt-dlp do not expose TikTok admin audience or retention rows. Post-level remeasure (views/likes/comments/shares/saves) is in Content Learning public engagement tables (2026-08-02).",
    },
    {
      platform: "YouTube",
      handle: "@Loom-idol-m",
      url: "https://www.youtube.com/@Loom-idol-m",
      role: "Loom/Pulso Shorts + public video archive",
      mainMetric: "5,907",
      mainLabel: "Studio views 2026-06-07~2026-08-02 · OAuth Analytics",
      stats: [
        ["Channel followers", "9"],
        ["Avg view % (Studio)", "67.25%"],
        ["Avg watch", "20s"],
        ["Top country", "KR 40.9%"],
        ["Watch minutes", "624"],
        ["Age / gender", "not exposed"],
      ],
      note:
        "YouTube Analytics OAuth (owner) on 2026-08-02. averageViewPercentage can exceed 100% on Shorts due to replays. Age/gender not queried in this pass. Do not treat as live dashboard.",
    },
  ],
  contentCases: [
    {
      title: "Loom / Pulso short-form loop",
      target:
        "창작 타깃 가설: 20대 초반 여성. (공개 API에 연령·성별·국가 인구통계 없음. 실제 시청자 인구통계로 표기하지 않음.)",
      intent:
        "AI 아이돌 IP의 트랙·핵심 영상·TikTok 클립·YouTube 공개 표면 운영 · 반응 신호의 다음 메시지·컷 설계 가설 환류",
      role:
        "IP 구조, 트랙/멤버/영상 흐름, AI 제작 루프, 게시 경로, 채널 신호 정리. 메시지·타깃 정렬·컷 구조의 최종 판단은 사람이 한다.",
      metrics:
        "채널 요약 last verified 2026-07-02: TikTok recent 30 9,097 views. 2026-08-02 remeasure: post-level views/likes/comments/shares/saves + derived rates. Country, completion, AVD, age/gender: not exposed via public API.",
    },
  ],
  /** Top public TikTok samples · remesured 2026-08-02 via yt-dlp */
  tiktokVideos: [
    {
      date: "2026-06-24",
      title: "ink-yeul #grokai #aiidol #kpop #virtualidol #ink",
      url: "https://www.tiktok.com/@loom_mm/video/7654903404963122452",
      views: 942,
      likes: 18,
      comments: 0,
      shares: 0,
      saves: 2,
    },
    {
      date: "2026-07-30",
      title: "Loom · Bouquet CF Different gazes meet",
      url: "https://www.tiktok.com/@loom_mm/video/7668260819439848725",
      views: 906,
      likes: 19,
      comments: 0,
      shares: 0,
      saves: 1,
    },
    {
      date: "2026-06-23",
      title: "#kpop #aiidol #ai #virtualidol #loom",
      url: "https://www.tiktok.com/@loom_mm/video/7654624880796699924",
      views: 896,
      likes: 45,
      comments: 0,
      shares: 0,
      saves: 0,
    },
    {
      date: "2026-06-23",
      title: "#loom #kpop #virtualidol #ai #aiidol",
      url: "https://www.tiktok.com/@loom_mm/video/7654618213472505109",
      views: 851,
      likes: 16,
      comments: 0,
      shares: 5,
      saves: 5,
    },
    {
      date: "2026-06-24",
      title: "ink-solo--rena#grokai #aiidol #kpop #virtualidol #ink",
      url: "https://www.tiktok.com/@loom_mm/video/7654903232178834709",
      views: 850,
      likes: 13,
      comments: 0,
      shares: 0,
      saves: 0,
    },
  ],
  /** Top public YouTube samples · remesured 2026-08-02 via yt-dlp */
  youtubeVideos: [
    {
      date: "2026-07-30",
      title: "Loom · They look at each other #Shorts",
      url: "https://www.youtube.com/shorts/xNfAkfhipSE",
      views: 2470,
      likes: 21,
      duration: "4s",
    },
    {
      date: "2026-07-30",
      title: "Loom · Bouquet CF · Different gazes meet #Shorts",
      url: "https://www.youtube.com/shorts/br8NKQIHjOQ",
      views: 1241,
      likes: 10,
      duration: "19s",
    },
    {
      date: "2026-07-29",
      title: "Loom · Rena · One chosen color starts the day #Shorts",
      url: "https://www.youtube.com/shorts/rxwn61IROQc",
      views: 1105,
      likes: 11,
      duration: "8s",
    },
    {
      date: "2026-08-01",
      title: "Four Routes. One Squad. | Loom #Shorts",
      url: "https://www.youtube.com/shorts/4-18kkZFh18",
      views: 601,
      likes: 10,
      duration: "34s",
    },
    {
      date: "2026-06-18",
      title: "Loom - World Cup Pulso / Section S03 - hidden pulse hook #Shorts",
      url: "https://www.youtube.com/shorts/l2cJP7Q9I8I",
      views: 355,
      likes: 1,
      duration: "22s",
    },
    {
      date: "2026-07-02",
      title: "Loom - Ink | AI K-pop Idol Music Video",
      url: "https://www.youtube.com/watch?v=TyONE0lKI2s",
      views: 94,
      likes: 3,
      duration: "2:42",
    },
  ],
} as const;
