import type { Slide } from "../types";

export const adsbSlides = [
  {
    no: 30,
    section: "ADSB",
    title: "ADSB Overview",
    label: "Second Main Case",
    accent: "violet",
    variant: "evidence",
    intent: "ADSB를 AHEYA의 부록이 아니라 두 번째 메인 콘텐츠 크리에이션 케이스로 소개한다.",
    claim:
      "Andersson Bell 산학공동연구에서 브랜드 리서치, 스토리보드, 생성 이미지, 보정, Kling 영상화까지 이어지는 15초 AI 숏폼 제작 케이스",
    include: [
      "Summary: 생성형 AI 기반 패션 브랜드 VIRTUAL CONTENT 개발 프로젝트",
      "Period: 2025.09.01-2025.11.07 산학공동연구",
      "My Role: 브랜드 분석, 모티프/훅 정리, 스토리보드 재작성, 프롬프트 방향, 피드백 반영",
      "Deliverables: 최종보고서, storyboard package, generated image set, cut sequence, final 15s short-form output",
    ],
    slots: [
      "프로젝트 요약: 생성형 AI 기반 패션 브랜드 VIRTUAL CONTENT / Andersson Bell brand-fit AI short-form",
      "역할: brand analysis / storyboard / prompt direction / feedback alignment",
      "툴: Midjourney, Gemini/Nano Banana, Photoshop, Kling",
      "산출물: 최종보고서, 스토리보드 패키지, 이미지 시안, 약 15초 숏폼",
    ],
    media: { src: "/adsb/adsb-cover.webp", alt: "ADSB cover visual", label: "Final visual direction" },
    links: [
      {
        label: "Instagram Reel",
        href: "https://www.instagram.com/reel/DRvZIP1EosJ/?igsh=c3Z3ZzFxN25zN205",
        description: "최종 숏폼 결과물 확인용 외부 링크",
      },
    ],
    note:
      "핵심은 'AI 이미지 생성'이 아니라 brand analysis -> storyboard -> visual generation -> correction -> Kling video -> feedback revision의 전체 제작 사이클이다.",
  },
  {
    no: 31,
    section: "ADSB",
    title: "Brand & Content Context",
    label: "Brand Context",
    accent: "cyan",
    variant: "matrix",
    intent: "왜 이 작업이 필요했는지, 브랜드 콘텐츠 관점에서 문제와 목표를 분리한다.",
    claim:
      "패션 브랜드 숏폼에서 제품 설명보다 먼저 읽혀야 하는 첫 프레임의 무드, 모티프, 컷 흐름",
    include: ["Brand context", "Creative challenge", "Objective", "Success condition"],
    slots: [
      "Brand situation: Andersson Bell tone and visual logic",
      "Challenge: open-ended AI generation caused tone diffusion",
      "Objective: fixed-angle sequence and brand-fit mood",
      "Success condition: 짧고 읽히는 15초 숏폼",
    ],
    table: {
      headers: ["구분", "내용", "콘텐츠 반영"],
      rows: [
        ["브랜드 과제", "한국과 스칸디나비아 감각의 대비, Expect the Unexpected, 유틸리티/해체주의/절제된 디테일을 숏폼으로 번역", "brand analysis, visual reference"],
        ["제작 문제", "초기 AI 생성은 이미지가 많아질수록 톤이 분산되고 시선이 흩어짐", "초기 콜라주/시안 비교"],
        ["목표", "브랜드 정체성, 세일즈 목적, 짧은 러닝타임에 맞는 단일 시각 흐름 구축", "스토리보드와 고정 앵글 sequence"],
        ["판단 기준", "예쁜 이미지보다 브랜드 적합성, 임팩트, 톤앤매너, 컷 흐름을 우선", "최종 15초 결과 프레임"],
      ],
    },
    media: { src: "/adsb/source-assets/adsb-key-msg.webp", alt: "ADSB key message visual", label: "Key message" },
    note:
      "최종보고서의 기준은 생성형 AI 활용 자체가 아니라 브랜드 정체성과 세일즈 목적을 반영한 영상 콘텐츠 제작 체계다.",
  },
  {
    no: 32,
    section: "ADSB",
    title: "Mood / Audience Insight",
    label: "Mood Insight",
    accent: "amber",
    variant: "matrix",
    intent: "ADSB를 감각적 취향이 아니라 브랜드 톤과 숏폼 소비 방식의 해석 결과로 보여준다.",
    claim:
      "Mutated Mundane, 신호등, 횡단보도, 도시적 고정 앵글을 유지하며 무드 희석과 시선 분산을 줄인 방향",
    include: ["Mutated Mundane", "Urban restraint", "First-frame impact", "Audience readability"],
    slots: [
      "Mutated Mundane motif",
      "Traffic light / crosswalk visual cue",
      "Fixed-angle mood board",
      "Audience first-frame rule",
    ],
    table: {
      headers: ["분석 요소", "본 내용", "콘텐츠 반영"],
      rows: [
        ["브랜드 톤", "실험적이지만 과한 판타지보다 도시적이고 절제된 인상", "고정 앵글, 도시 배경, 제한된 오브젝트 중심"],
        ["핵심 모티프", "Mutated Mundane, mixtape of old favorites made new, 신호등, 횡단보도, 일상의 비틀림", "브랜드 무드가 한 컷 안에서 바로 읽히도록 반복"],
        ["무드 기준", "밝고 컬러풀한 정오 톤, 도시/외곽 공간 대비, 과거 문화유산을 현대 일상으로 옮기는 오마주 검토", "이미지 톤앤무드, 배경 후보, key message"],
        ["AI 리스크", "콜라주와 과한 생성 효과는 무드 희석, 시선 분산, 임팩트 부족으로 이어짐", "콜라주 방식 폐기, fixed-angle sequence로 재구성"],
      ],
    },
    media: { src: "/adsb/source-assets/adsb-moodboard.webp", alt: "ADSB moodboard", label: "Moodboard source" },
  },
  {
    no: 33,
    section: "ADSB",
    title: "Creative Strategy",
    label: "Creative Direction",
    accent: "aqua",
    variant: "process",
    intent: "브랜드 무드 해석을 실제 콘텐츠 방향과 숏폼 장면 구조로 전환한다.",
    claim:
      "초기 확산형 아이디어를 줄이고 브랜드 무드가 선명하게 읽히는 고정 앵글 기반 컷 시퀀스로 재설계",
    include: [
      "브랜드 분석으로 훅, 모티프, 장면 축을 먼저 정리",
      "실무 피드백을 concept correction과 production rule로 변환",
      "콜라주 중심 방향은 무드 희석과 임팩트 부족 때문에 폐기",
      "고정 앵글 기반으로 배경, 인물, 오브젝트를 재배치",
      "짧은 러닝타임에 맞게 장면 수와 반복 컷을 줄임",
    ],
    slots: [
      "Creative Direction: Mutated Mundane in fixed-angle sequence",
      "Feedback Rule: idea diffusion을 줄이고 메시지/톤 일관성 강화",
      "Discarded: collage-heavy direction",
      "Kept: traffic light / crosswalk / urban and noon mood",
      "Output Rule: 15s, restrained, brand-fit",
    ],
    process: [
      "Brand analysis",
      "Motif selection",
      "Storyboard rewrite",
      "Collage direction discarded",
      "Fixed-angle sequence",
      "15s compression",
    ],
    media: { src: "/adsb/adsb-planning-draft.webp", alt: "ADSB planning draft", label: "Planning draft" },
    note:
      "피드백을 aesthetic commentary가 아니라 production rule로 읽고, 장면을 더하는 대신 방향을 좁힌 점이 이 케이스의 핵심 판단이다.",
  },
  {
    no: 34,
    section: "ADSB",
    title: "AI Production Workflow",
    label: "AI Workflow",
    accent: "violet",
    variant: "process",
    intent: "AI를 단순 생성 도구가 아니라 제작 워크플로우로 활용한 방식을 단계별로 보여준다.",
    claim:
      "Midjourney, Gemini/Nano Banana, Photoshop, Kling을 이미지 시안-보정-영상화-피드백 수정의 production loop로 연결",
    include: [
      "Brand analysis",
      "Storyboard and cut logic",
      "Midjourney image generation",
      "Gemini/Nano Banana image correction",
      "Photoshop visual refinement",
      "Kling video generation",
      "Frame and runtime compression",
      "Stakeholder feedback revision",
    ],
    slots: [
      "Toolchain map",
      "Image-to-video workflow",
      "Correction rule: brand fit, impact, tone, cut flow",
      "Feedback loop: report -> storyboard -> visual -> video",
      "Final asset package",
    ],
    process: [
      "Brand analysis",
      "Storyboard",
      "Midjourney generation",
      "Gemini/Nano Banana correction",
      "Photoshop refinement",
      "Kling video",
      "Frame / runtime edit",
      "Feedback revision",
    ],
    note:
      "AI was used not only for image generation, but as a workflow for turning brand mood, storyboard, generated frames, and stakeholder feedback into a short-form output.",
  },
  {
    no: 35,
    section: "ADSB",
    title: "Prompt & Iteration Process",
    label: "Prompt System",
    accent: "cyan",
    variant: "matrix",
    intent: "프롬프트를 그냥 작성한 것이 아니라 반복 기준과 선별 기준을 갖고 운영했음을 보여준다.",
    claim:
      "더 많은 이미지를 만드는 과정이 아니라 브랜드 적합도가 낮은 방향을 제거하고 남길 컷의 규칙을 정한 반복 과정",
    include: ["Prompt structure", "Iteration process", "Discard rule", "Selection criteria"],
    slots: [
      "Prompt structure: motif, subject, pose, background, camera, lighting, mood",
      "Iteration log: generate -> compare -> discard -> revise",
      "Discarded examples: collage, tone diffusion, weak impact",
      "Selected examples: fixed-angle, clear motif, stronger first frame",
    ],
    table: {
      headers: ["반복 기준", "수정 내용", "선택/폐기 기준"],
      rows: [
        ["브랜드 적합성", "브랜드 리서치와 무드보드에 맞지 않는 과한 생성 이미지를 제거", "Andersson Bell 톤과 모티프가 보이는가"],
        ["장면 집중도", "콜라주처럼 시선이 분산되는 방향을 폐기", "첫 프레임의 목적과 오브젝트가 바로 읽히는가"],
        ["영상화 가능성", "정지 이미지를 컷 단위 sequence로 다시 정리", "Kling으로 움직임을 붙였을 때 무드가 유지되는가"],
        ["피드백 반영", "실무진 피드백을 기준으로 구도, 색, 리듬을 보정", "취향보다 구조적 문제를 해결했는가"],
      ],
    },
    media: { src: "/adsb/adsb-images-draft.webp", alt: "ADSB generated draft variants", label: "Draft variants" },
  },
  {
    no: 36,
    section: "ADSB",
    title: "Output / Storyboard",
    label: "Output Structure",
    accent: "amber",
    variant: "matrix",
    intent: "선별 이미지, 영상 프롬프트, 숏폼 스토리보드를 실제 산출물 구조로 연결한다.",
    claim:
      "스토리보드, 컷별 대표 이미지, Kling 영상, 약 15초 러닝타임으로 정리된 숏폼 패키지",
    include: [
      "Storyboard package",
      "Generated image set",
      "Cut logic / sequence structure",
      "Kling-based final short-form",
      "Process board, prompt variants, feedback revision trail",
    ],
    slots: [
      "Storyboard package",
      "Generated frame set",
      "Cut sequence",
      "Final 15s output",
      "Instagram reel / public proof",
    ],
    table: {
      headers: ["Scene", "Duration", "Visual", "Purpose"],
      rows: [
        ["1", "0-2s", "횡단보도/도시 배경의 강한 첫 프레임", "브랜드 무드와 장소감 고정"],
        ["2", "2-5s", "인물, 오브젝트, 쇼핑백이 한 컷 안에서 정리된 장면", "제품/룩과 캐릭터 인상 연결"],
        ["3", "5-9s", "고정 앵글 기반의 움직임과 컷 전환", "콜라주보다 안정적인 흐름 확보"],
        ["4", "9-13s", "선별 컷의 반복 최소화와 리듬 조정", "Kling 생성 후 러닝타임 과다 문제 해결"],
        ["5", "13-15s", "브랜드 인상이 남는 closing frame", "짧고 읽히는 최종 숏폼으로 마무리"],
      ],
    },
    media: { src: "/adsb/adsb-production.webp", alt: "ADSB production board", label: "Production board" },
    links: [
      {
        label: "Final Reel",
        href: "https://www.instagram.com/reel/DRvZIP1EosJ/?igsh=c3Z3ZzFxN25zN205",
        description: "스토리보드와 제작 흐름이 수렴된 최종 15초 숏폼",
      },
    ],
  },
  {
    no: 37,
    section: "ADSB",
    title: "Learning & What This Proves",
    label: "Learning",
    accent: "aqua",
    variant: "evidence",
    intent: "ADSB를 통해 증명되는 콘텐츠 기획, AI 제작 워크플로우, 브랜드 해석 역량을 정리한다.",
    claim:
      "생성형 AI 결과물보다 브랜드 해석과 피드백을 기준으로 약한 방향을 버리고 더 읽히는 결과로 수렴시키는 판단력",
    include: [
      "Learning: 결과 품질은 프롬프트보다 브랜드 해석과 선택/폐기 판단에 크게 좌우됨",
      "Learning: 콜라주처럼 화려한 방향이 항상 브랜드-fit 결과는 아님",
      "Learning: 실무 피드백은 취향 평가가 아니라 다음 production rule로 변환해야 함",
      "Learning: 영상화 단계에서는 런타임, 반복 컷, 시선 흐름까지 같이 조정해야 함",
      "What this proves: brand analysis, storyboard system, AI toolchain, feedback alignment, final output delivery",
    ],
    slots: [
      "Learning: brand interpretation matters",
      "Learning: discard weak direction fast",
      "Learning: use feedback as production rule",
      "What This Proves: structured AI creative direction",
    ],
    media: { src: "/adsb/adsb-kling-product.webp", alt: "ADSB Kling product output", label: "Video-ready output" },
    note:
      "마지막 문장은 'AI를 잘 다룬다'가 아니라 '브랜드-fit 콘텐츠 방향을 선택하고 실제 산출물까지 수렴시킬 수 있다'로 닫는다.",
  },
] satisfies Slide[];
