import type { Slide } from "../types";

export const aheyaAppendixSlides = [
  {
    no: 49,
    section: "Appendix",
    title: "Internal Trust API Boundary",
    label: "Technical Boundary Evidence",
    accent: "violet",
    variant: "matrix",
    intent: "Trust API를 본문 제품 스토리와 분리된 내부/runtime API boundary evidence로 정리한다.",
    claim: "Internal runtime evidence only - not public GTM result. Trust API는 evaluation, signal, trust memory를 다루는 internal/runtime boundary evidence",
    include: ["Public product flow", "Trust API", "Signal memory", "Boundary"],
    slots: ["public product headline 아님", "resolve -> signals -> trust memory", "support/feedback semantics reuse", "external demand proof 제외"],
    table: {
      headers: ["Area", "Public product flow", "Trust API"],
      rows: [
        ["Portfolio placement", "Main body", "Appendix only"],
        ["Public meaning", "Founder first-signal loop", "Internal trust/evaluation layer"],
        ["Main loop", "support -> Good/Improve -> optional proof", "resolve -> signals -> trust memory"],
        ["Evidence type", "product flow, X/content surface", "API docs, decision logs, runtime signal structure"],
        ["Safe claim", "support/feedback/proof system design", "API boundary and runtime contract design"],
      ],
    },
    note: "Do not describe Trust API as the main AHEYA product, marketed GTM result, or proven external demand loop.",
  },
  {
    no: 50,
    section: "Appendix",
    title: "Onchain Verification Boundary",
    label: "Not Adoption Proof",
    accent: "cyan",
    variant: "matrix",
    intent: "ETH/SOL onchain material을 wallet support/proof substrate로만 보여준다.",
    claim: "Verification substrate - not adoption proof. wallet action을 support/proof로 바꾸는 substrate로만 제한",
    include: ["Public support flow", "EVM/Base", "Solana", "Boundary"],
    slots: ["direct-send verify", "wallet-signed publish context", "registry/claim wiring", "no deployment/adoption claim"],
    table: {
      headers: ["Layer", "What it shows", "Boundary"],
      rows: [
        ["Public support flow", "live idea -> support -> Good/Improve -> optional proof", "public product story"],
        ["EVM/Base", "direct-send verify, registry/claim wiring context", "deployment/adoption proof 아님"],
        ["Solana", "wallet connect, wallet-signed publish, direct-send support runtime", "legacy program-first runtime claim 금지"],
        ["Portfolio", "January smart-contract work as verification foundation", "개선 수치 과장 금지"],
      ],
    },
    media: { src: "/aheya/ppt/aheya-onchain-verification-rail.svg", alt: "AHEYA onchain verification rail", label: "Onchain rail" },
  },
  {
    no: 51,
    section: "Appendix",
    title: "Contract Planning Artifacts",
    label: "Not Deployment Claim",
    accent: "aqua",
    variant: "evidence",
    intent: "스마트컨트랙트 구현 흔적을 raw code screenshot 없이 source evidence card로 보여준다.",
    claim: "Contract planning artifacts - not deployment claim. EVM registry와 Solana Anchor program은 planning artifact로만 사용",
    include: ["EVM source card", "Solana source card", "Not-found boundary"],
    slots: [
      "EVM: EIP-712 permit registration, operator-gated funding records, seed metadata",
      "Solana: Anchor program planning, register_idea, support_native, record_funding_attested",
      "GitHub/editor code screenshots are excluded",
      "Not used as a source-verified implementation claim; treated only as generated / planning artifact",
    ],
    media: { src: "/aheya/ppt/aheya-contract-source-evidence-cards.svg", alt: "AHEYA contract source evidence cards", label: "Source evidence cards" },
    note: "Public deck should not expose private repo URLs, raw source blocks, tokens, or deployment/adoption claims.",
  },
  {
    no: 52,
    section: "Appendix",
    title: "Planning Lineage, Not Current Product Truth",
    label: "Planning Boundary",
    accent: "amber",
    variant: "matrix",
    intent: "Raven/Aheaya planning을 현재 public support/feedback flow와 분리된 기획/문서화 evidence로 정리한다.",
    claim: "Planning lineage - not current product truth. broad reward/quest/funding system에서 support + feedback + proof rail 중심의 first-signal loop로 줄인 판단의 흔적",
    include: ["Legacy flow", "Requirements", "Roadmap", "KPI templates", "January narrowing"],
    slots: ["Founder/funder flow", "Creator flow", "Sprint requirements", "Community/SNS/KOL KPI templates"],
    table: {
      headers: ["Earlier Raven planning", "January 2026 AHEYA pivot"],
      rows: [
        ["funding + quest + helper + reward + point/token loop", "support + feedback + proof rail"],
        ["multiple participation lanes and reward mechanics", "simpler first-signal loop"],
        ["token/DAO/claim and marketplace assumptions", "wallet/proof substrate kept, heavy reward language reduced"],
        ["community/KOL/KPI templates", "KPI/event design separated from results"],
      ],
    },
    media: { src: "/aheya/legacy/pre-january-product-evolution.svg", alt: "Pre-January product evolution", label: "Legacy planning map" },
    note: "Use as planning/documentation evidence only. Do not present as current product truth or live adoption evidence.",
  },
] satisfies Slide[];
