import type { Slide } from "../types";

export const aheyaAppendixSlides = [
  {
    no: 49,
    section: "Appendix",
    title: "Trust API Boundary",
    label: "Appendix A",
    accent: "violet",
    variant: "matrix",
    intent: "Trust API를 본문 제품 스토리와 분리된 내부/runtime API boundary evidence로 정리한다.",
    claim: "Trust API는 public GTM 성과가 아니라 evaluation, signal, trust memory를 다룬 내부 API/runtime layer",
    include: ["Public product flow", "Trust API", "Signal memory", "Boundary"],
    slots: ["public product headline 아님", "resolve -> signals -> trust memory", "support/feedback semantics reuse", "external demand proof 제외"],
    table: {
      headers: ["Area", "Public product flow", "Trust API"],
      rows: [
        ["Portfolio placement", "Main body", "Appendix only"],
        ["Public meaning", "Founder first-signal loop", "Internal trust/evaluation layer"],
        ["Main loop", "support -> Good/Improve -> optional proof", "resolve -> signals -> trust memory"],
        ["Evidence type", "product flow, X/content surface", "API docs, decision logs, runtime signal structure"],
        ["Safe claim", "support/feedback/proof system design", "API boundary and runtime contract design"],
      ],
    },
    note: "Do not describe Trust API as the main AHEYA product, marketed GTM result, or proven external demand loop.",
  },
  {
    no: 50,
    section: "Appendix",
    title: "Onchain Verification Rail",
    label: "Appendix B",
    accent: "cyan",
    variant: "matrix",
    intent: "ETH/SOL onchain material을 wallet support/proof substrate로만 보여준다.",
    claim: "wallet action을 support/proof로 바꾸는 verification substrate, not adoption proof",
    include: ["Public support flow", "EVM/Base", "Solana", "Boundary"],
    slots: ["direct-send verify", "wallet-signed publish context", "registry/claim wiring", "no traction claim"],
    table: {
      headers: ["Layer", "What it shows", "Boundary"],
      rows: [
        ["Public support flow", "live idea -> support -> Good/Improve -> optional proof", "public product story"],
        ["EVM/Base", "direct-send verify, registry/claim wiring context", "deployment/adoption proof 아님"],
        ["Solana", "wallet connect, wallet-signed publish, direct-send support runtime", "legacy program-first runtime claim 금지"],
        ["Portfolio", "January smart-contract work as verification foundation", "개선 수치 과장 금지"],
      ],
    },
    media: { src: "/aheya/ppt/aheya-onchain-verification-rail.svg", alt: "AHEYA onchain verification rail", label: "Onchain rail" },
  },
  {
    no: 51,
    section: "Appendix",
    title: "Contract Artifacts Written",
    label: "Appendix B-2",
    accent: "aqua",
    variant: "evidence",
    intent: "스마트컨트랙트 구현 흔적을 raw code screenshot 없이 source evidence card로 보여준다.",
    claim: "EVM registry와 Solana Anchor program은 technical artifact proof로만 사용",
    include: ["EVM source card", "Solana source card", "Not-found boundary"],
    slots: [
      "EVM: EIP-712 permit registration, operator-gated funding records, seed wallet metadata",
      "Solana: Anchor program, register_idea, support_native, record_funding_attested",
      "GitHub/editor code screenshots are excluded",
      "AheyaDustTokenE2E source not found; generated artifact만으로 source evidence 처리 금지",
    ],
    media: { src: "/aheya/ppt/aheya-contract-source-evidence-cards.svg", alt: "AHEYA contract source evidence cards", label: "Source evidence cards" },
    note: "Public deck should not expose private repo URLs, raw source blocks, tokens, or deployment/adoption claims.",
  },
  {
    no: 52,
    section: "Appendix",
    title: "Pre-January Planning Lineage",
    label: "Appendix C",
    accent: "amber",
    variant: "matrix",
    intent: "Raven/Aheaya planning을 현재 public support/feedback flow와 분리된 기획/문서화 evidence로 정리한다.",
    claim: "Broad reward/quest/funding system에서 narrower support + feedback + proof rail로 줄인 planning lineage",
    include: ["Legacy flow", "Requirements", "Roadmap", "KPI templates", "January narrowing"],
    slots: ["Founder/funder flow", "Creator flow", "Sprint requirements", "Community/SNS/KOL KPI templates"],
    table: {
      headers: ["Earlier Raven planning", "January 2026 AHEYA pivot"],
      rows: [
        ["funding + quest + helper + reward + point/token loop", "support + feedback + proof rail"],
        ["multiple participation lanes and reward mechanics", "simpler first-signal loop"],
        ["token/DAO/claim and marketplace assumptions", "wallet/proof substrate kept, heavy reward language reduced"],
        ["community/KOL/KPI templates", "KPI/event design separated from results"],
      ],
    },
    media: { src: "/aheya/legacy/pre-january-product-evolution.svg", alt: "Pre-January product evolution", label: "Legacy planning map" },
    note: "Use as planning/documentation evidence only. Do not present as current product truth or live adoption evidence.",
  },
] satisfies Slide[];
