import type { Slide } from "../types";

export const aheyaSlides = [
  {
    no: 9,
    section: "AHEYA",
    title: "AHEYA Overview",
    label: "Flagship Case",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaOverview",
    intent: "AHEYA 프로젝트의 역할, 기간, 산출물, 본문/appendix 경계를 한 장에서 정리한다.",
    claim: "AHEYA는 초기 제품/아이디어 페이지를 열고,\n사용자가 작은 지지 의사와 짧은 피드백을 남길 수 있게 만든 product / GTM / content signal review case입니다.",
    include: ["Role", "Evidence", "Boundary", "Appendix"],
    slots: [
      "Role: product planning, GTM framing, content system, signal review",
      "Main evidence: product flow, public page, X content, KPI/event design, decision log",
      "Boundary: 성과/전환 입증이 아니라 초기 제품, 메시지, 콘텐츠 신호 검토 사례",
      "Appendix: technical verification, onchain layer, earlier planning lineage",
    ],
    media: { src: "/aheya/aheyabaraya-homepage-2026-04-28.png", alt: "AHEYA public surface", label: "AHEYA public surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
    note: "Commercial outcome and demand claims are excluded.",
  },
  {
    no: 10,
    section: "AHEYA",
    title: "Scope Narrowing Timeline",
    label: "Context",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaTimeline",
    intent: "넓은 초기 제품 기획에서 AHEYA public response flow와 public X CTA로 좁혀진 흐름을 날짜순으로 보여준다.",
    claim: "2025년 11월의 넓은 기획 범위를\n공개 아이디어, 지지 의사, 피드백, 응답 기록 중심으로 좁힌 과정",
    include: ["Planning baseline", "January narrowing", "February X CTA", "March GTM", "April response-flow baseline"],
    slots: ["Broad planning", "Small response narrowing", "Public copy test", "GTM bridge", "Response-flow baseline"],
    table: {
      headers: ["시점", "변화", "포트폴리오 의미"],
      rows: [
        ["2025-11", "Funding, reward, quest, KPI template까지 넓게 설계", "초기 기획 범위와 구조화 능력의 legacy evidence"],
        ["2026-01", "Reward/funding thesis를 작은 지지 의사와 짧은 피드백 방향으로 축소", "제품 특성 전환과 technical layer 정리"],
        ["2026-02", "X에서 testnet/link CTA와 AI-native first-response framing이 등장", "public language iteration 시작 시점"],
        ["2026-03", "wallet-adjacent builder sourcing, X reply/DM guideline 정리", "GTM/content 언어와 대상 세그먼트 연결"],
        ["2026-04", "Public idea page, response verification, KPI/event design, appendix boundary 정리", "현재 본문 제품 스토리의 기준선"],
      ],
    },
  },
  {
    no: 11,
    section: "AHEYA",
    title: "Research → Problem → Product Decision",
    label: "Research",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaResearchSolution",
    intent: "BP/research에서 본 Web3 참여 문제와 builder의 첫 반응 병목을 제품 판단으로 연결한다.",
    claim: "토큰 보상 중심 행동은 실제 제품 참여로 잘 이어지지 않고,\nbuilder는 demo 이후 첫 반응과 명확한 피드백에서 막힌다",
    include: ["Residual onchain action", "Builder first-response gap", "AHEYA narrowing"],
    slots: ["Reward loop", "Builder growth gap", "Small response path"],
    table: {
      headers: ["Research summary", "Problem connection", "AHEYA solution"],
      rows: [
        [
          "Web3 사용자는 보상을 위해 airdrop, quest, community, SNS 행동을 반복한다.",
          "하지만 그 행동은 실제 제품 사용, 피드백, 신뢰 가능한 반응 기록으로 잘 번역되지 않는다.",
          "AHEYA는 행동을 공개 아이디어 열람, 작은 지지 의사, 긍정/개선 피드백으로 좁혔다.",
        ],
        [
          "AI-assisted builder는 demo, docs, GitHub, launch post를 더 빠르게 만들 수 있다.",
          "하지만 live demo 이후 첫 사용자, 명확한 피드백, 업데이트에 쓸 수 있는 반응 기록은 여전히 부족하다.",
          "제품은 broad platform claim이 아니라 public idea page와 lightweight response path에서 시작한다.",
        ],
        [
          "Wallet/onchain은 참여 확인과 기록의 기술 기반으로는 유용하다.",
          "하지만 첫 touchpoint에서 mechanism-first 설명은 진입 이해를 어렵게 만든다.",
          "기술 기반은 UX 뒤에 두고, GTM은 builder가 원하는 첫 반응 문제에서 출발했다.",
        ],
      ],
    },
  },
  {
    no: 12,
    section: "AHEYA",
    title: "Audience Motion Map",
    label: "Product Map",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaProductSurfaceMap",
    intent: "영상 기반으로 maker와 early user가 어떤 흐름을 타는지 사용자 행동 기준으로 보여준다.",
    claim: "영상은 early user의 작은 반응과 builder의 검토 화면이\n어떻게 하나의 response path로 이어지는지 보여준다",
    include: ["Early user motion", "Builder motion", "System boundary"],
    slots: [
      "Early user: 아이디어를 열고 작은 지지 의사와 quick feedback을 남김",
      "Maker / builder: 받은 반응을 reviewable response로 확인",
      "System layer: verification과 review는 user-facing flow 뒤에 둠",
      "Boundary: 영상은 flow evidence이지 product outcome evidence가 아님",
    ],
    gallery: [
      {
        src: "/aheya/corerail-support-vid.mp4",
        alt: "AHEYA early-user action flow video",
        label: "Early-user action",
        type: "video",
        poster: "/aheya/aheya-home-hero.webp",
        startTime: 1,
        caption: "idea open -> small backing intent -> quick feedback",
      },
      {
        src: "/aheya/aheya-corerail-creator.mp4",
        alt: "AHEYA builder-side response review video",
        label: "Builder review",
        type: "video",
        poster: "/aheya/aheya-lane-panels.webp",
        startTime: 1,
        caption: "feedback and response record review",
      },
    ],
  },
  {
    no: 13,
    section: "AHEYA",
    title: "Screen Evidence Map",
    label: "Flow Evidence",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFeatureEvidenceMap",
    intent: "정적 화면 캡처를 기능별로 매칭해 어떤 화면이 어떤 product function을 맡는지 보여준다.",
    claim: "화면 캡처는 public idea, explore, action, record가\n어디에 구현되어 있는지 분리해서 보여준다",
    include: ["Public idea", "Explore", "Action", "Record"],
    slots: [
      "Public idea page: builder가 idea/project surface를 여는 화면",
      "Explore surface: creator/builder entry와 discovery surface",
      "Action surface: early user가 작은 지지 의사와 quick feedback을 남기는 화면",
      "Response record: 이후 업데이트 판단에 참고할 수 있는 기록",
    ],
    gallery: [
      {
        src: "/aheya/page-assets/screens/aheya-aheya-mainpage.webp",
        alt: "AHEYA public idea page screenshot",
        label: "Public idea",
        caption: "builder가 여는 idea/project surface",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-explore.webp",
        alt: "AHEYA explore screenshot",
        label: "Explore",
        caption: "creator/builder discovery surface",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-apppage.webp",
        alt: "AHEYA app page action screenshot",
        label: "Action page",
        caption: "backing intent and feedback action surface",
      },
      {
        src: "/aheya/aheya-lane-panels.webp",
        alt: "AHEYA response record lane panels",
        label: "Response record",
        caption: "reviewable response fields",
      },
    ],
  },
  {
    no: 14,
    section: "AHEYA",
    title: "First Target Hypothesis",
    label: "Prioritization",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionCards",
    intent: "Prioritization & Goals와 Hypotheses를 crypto/wallet-adjacent live-demo builder entry 중심으로 한 장에 묶는다.",
    claim: "첫 대상은 모든 Web3 사용자가 아니라,\nlive demo 이후 첫 반응과 명확한 피드백이 필요한 AI-native builder",
    include: ["Live-demo builder", "First offer", "Minimal flow", "Measurement goal"],
    slots: ["Live-demo builder first", "Outcome before Web3 mechanics", "Simple response path", "Reward/technical depth postponed"],
    table: {
      headers: ["우선순위", "선택", "이유"],
      rows: [
        ["Target segment", "AI-native builder, crypto product opener, rough live demo maker를 simple response path로 끌어오기", "builder가 먼저 들어와야 첫 반응과 기록 가능한 피드백이 생김"],
        ["Initial value proposition", "첫 사용자, 명확한 피드백, 업데이트에 참고할 반응 기록을 먼저 제안", "token/contract 설명보다 maker outcome이 진입 마찰을 낮춤"],
        ["MVP flow kept", "public idea page, small backing intent, quick positive/improvement feedback, response record", "처음 보는 사람도 이해할 수 있는 가장 작은 Web3 참여 행동"],
        ["What to measure", "content discovery, page open, backing/feedback/record intent를 분리 측정", "observed response와 measurement plan assumptions를 분리"],
      ],
    },
  },
  {
    no: 15,
    section: "AHEYA",
    title: "Product Direction",
    label: "Product Strategy",
    accent: "aqua",
    variant: "process",
    custom: "aheyaCoreRail",
    intent: "AHEYA의 현재 본문 제품 구조를 외부 사용자가 보는 흐름으로 고정한다.",
    claim: "public idea page -> small backing intent -> quick feedback -> response record",
    include: ["Idea page", "Backing intent", "Feedback", "Response record"],
    slots: ["Reward-first quest/funding framing 제외", "Token/contract-first explanation 제외", "Technical verification은 appendix로 분리", "Conversion or outcome claim 아님"],
    process: ["Public idea page", "Small backing intent", "Quick feedback", "Response record"],
  },
  {
    no: 16,
    section: "AHEYA",
    title: "User Journey & Flow",
    label: "Flow",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFlowHero",
    intent: "SNS 발견부터 작은 지지 의사/피드백까지의 짧은 경로를 보여준다.",
    claim: "X/content에서 public idea page로 들어와\n작은 지지 의사와 quick feedback으로 이어지는 흐름",
    include: ["See", "Open", "Understand", "Support", "Feedback", "Record"],
    slots: [
      "첫 touchpoint는 X/content 또는 demo note",
      "project page에서 idea와 action path를 이해",
      "지지 의사와 feedback은 reviewable response record로 남김",
      "screenshot/video는 flow evidence이지 funnel outcome evidence가 아님",
    ],
    process: ["Discover", "Open", "Act", "Respond", "Record"],
  },
  {
    no: 17,
    section: "AHEYA",
    title: "MVP Scope",
    label: "Scope Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMvpCut",
    intent: "Included / Excluded Features와 Feature Prioritization을 명확히 분리한다.",
    claim: "builder entry와 first useful response에 필요한 것만 남기고 reward-first framing과 technical depth는 뒤로 뺐다",
    include: ["Included", "Excluded", "Priority", "Boundary"],
    slots: ["Builder-facing idea surface", "Backing intent + quick feedback", "Response record + event hooks", "Reward/technical depth deferred"],
    table: {
      headers: ["Cut line", "MVP에 남긴 것", "판단 기준"],
      rows: [
        ["Included", "public idea page, project surface, builder problem hook", "builder가 작은 반응 경로에 들어오는 입구"],
        ["Included", "small backing intent, positive/improvement feedback, response review", "지지 의사와 피드백이 첫 observed response로 남는 최소 행동"],
        ["Priority", "KPI/event hooks, review queue, response memory", "재사용 가능한 response record와 다음 판단 구조"],
        ["Sequencing", "manual sourcing -> response sprint -> weekly review -> next lane decision", "12주 계획은 성과 예측이 아니라 운영 리듬과 학습 단위로 사용"],
        ["Deferred", "reward-first public framing, token launch, technical verification as front-door story, heavy automation", "첫 entry clarity를 흐리는 요소 제거"],
      ],
    },
  },
  {
    no: 18,
    section: "AHEYA",
    title: "Documentation & Decision Trace",
    label: "PM Artifacts",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaPlanningBoard",
    intent: "PRD, user stories, wireframe, roadmap, GTM, KPI, decision log를 실행 메모리로 연결한다.",
    claim: "문서 제목만 보여주지 않고,\n날짜, 문서 유형, evidence cue, 사용된 판단을 함께 묶은 sanitized trace",
    include: ["PRD", "User Stories", "Wireframe", "Roadmap", "KPI/SQL", "Decision log"],
    slots: ["AI-assisted documentation", "Legacy docs map", "Drive source map", "Read/not-reviewed boundary"],
    table: {
      headers: ["Artifact", "Purpose", "Evidence cue", "Used for", "Boundary"],
      rows: [
        ["BP / Problem Thesis", "problem definition", "2026-03~04 BP/problem memo: reward-loop participation + builder growth gap cue", "problem slide and target hypothesis", "current commitment 아님"],
        ["Marketing / Ops Docs", "target and GTM", "2026-03 strategy notes: wallet-adjacent front door + reply/DM workflow cue", "GTM bridge and message ladder", "sales/partnership result claim 금지"],
        ["Flow / Code Map", "product flow", "2026-04 flow/code map: public idea, backing intent, feedback, response record cue", "screen evidence and user flow", "raw code screenshot 제외"],
        ["KPI / SQL Notes", "measurement design", "KPI/SQL addendum: content, page, backing, feedback event split cue", "measurement board and signal read", "read-only snapshot 전 숫자 제한"],
        ["Decision Log / Handoff", "PM judgment", "handoff/decision log: keep, defer, appendix boundary cue", "scope cut and final learning", "인과 과장 금지"],
      ],
    },
  },
  {
    no: 19,
    section: "AHEYA",
    title: "Measurement Design Board",
    label: "KPI / SQL",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaKpiBoard",
    intent: "KPI/SQL을 성과 숫자가 아니라 다음 판단을 위한 tracking plan으로 표현한다.",
    claim: "유입이 생겼을 때 무엇을 보고 판단할지 KPI tree, event source, SQL-ready use로 분리",
    include: ["KPI tree", "Event source", "SQL readiness", "Decision use"],
    slots: [
      "This is measurement design, not a performance result.",
      "Event examples: content_view, landing_visit, project_open",
      "Event examples: backing_start, feedback_submit, response_reviewed",
      "SQL cue: content/page/action/feedback 단위 집계",
      "Final number requires read-only snapshot",
    ],
    process: ["Content discovery", "Page open", "Backing intent", "Feedback / record", "Decision"],
    table: {
      headers: ["Metric", "Event source", "SQL-readiness", "Decision use"],
      rows: [
        ["Discovery", "public post surface, visual hook", "post URL, date, phase, metric field", "어떤 hook을 다음 content에 남길지 판단"],
        ["Product entry", "site visit, project open, CTA click", "page/event naming and source split", "content 관심과 product 이해를 분리"],
        ["Intent", "backing start, wallet intent", "intent event and session boundary", "mechanism 설명 이후 행동 의도 확인"],
        ["Response quality", "backing status, feedback submitted, response reviewed", "aggregate query-ready status", "업데이트에 참고 가능한 response만 남김"],
        ["SQL use", "content/page/action/feedback aggregate", "COUNT/FILTER query-ready event split", "성과가 아니라 다음 판단 질문을 준비"],
      ],
    },
  },
  {
    no: 20,
    section: "AHEYA",
    title: "GTM Strategy",
    label: "GTM",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaGtmBridge",
    intent: "builder와 wallet-adjacent user를 Web3 mechanism이 아니라 first-response 문제로 연결하는 GTM bridge를 보여준다.",
    claim: "1차 ICP는 live demo를 가진 AI-native builder;\nwallet-adjacent user는 작은 참여 행동의 보조 audience",
    include: ["Who", "Trigger", "Offer", "Bridge"],
    slots: ["AI-native live demo builder", "Live demo but weak first response", "Focused response pilot", "Outcome before mechanism"],
    table: {
      headers: ["GTM element", "정의", "표현 원칙"],
      rows: [
        ["Target", "AI-native builder or crypto product opener with a live demo", "manual audience discovery 가능한 범위로 좁힘"],
        ["Trigger", "live demo 이후 first users / feedback / response record가 약함", "builder pain을 먼저 말함"],
        ["Offer", "explore the idea, leave small backing intent, give quick feedback", "wallet/onchain은 관심 이후 technical layer로 설명"],
        ["Bridge", "builder outcome -> lightweight Web3 participation", "token/contract보다 first user response로 끌어옴"],
      ],
    },
  },
  {
    no: 21,
    section: "AHEYA",
    title: "Messaging Framework",
    label: "Message",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMessageLadder",
    intent: "cold/warm/hot 접근 단계별로 내부 mechanism을 외부 메시지로 바꾼다.",
    claim: "Build는 빨라졌지만,\n첫 사용자 반응과 명확한 피드백은 여전히 느리다",
    include: ["Problem", "Offer", "Action", "Boundary"],
    slots: ["Problem: first user response is still slow", "Offer: live demo -> small response path", "Action: open, try, leave one clear response", "Boundary: reward thesis를 public test처럼 쓰지 않음"],
    table: {
      headers: ["Message layer", "Copy direction", "주의점"],
      rows: [
        ["Problem", "Build는 빨라졌지만 첫 반응은 여전히 느림", "성과를 약속하지 않음"],
        ["Offer", "Live demo를 작은 반응 경로로 바꿈", "수요 입증 표현 금지"],
        ["Action", "아이디어를 열고, 흐름을 써보고, 한 줄 반응을 남김", "내부 용어는 짧게 보조 설명"],
        ["Boundary", "This does not claim market demand or funnel performance.", "reward-first quest 문장으로 쓰지 않음"],
      ],
    },
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-27.png",
        alt: "AHEYA public X post screenshot used as messaging evidence",
        label: "Public copy evidence",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        caption: "first-response / response-record public copy cue",
      },
    ],
  },
  {
    no: 22,
    section: "AHEYA",
    title: "Channel Test Plan",
    label: "Launch",
    accent: "violet",
    variant: "process",
    custom: "aheyaLaunchLoop",
    intent: "X, website/app, direct replies를 launch 성과가 아니라 language/content test surface로 분리한다.",
    claim: "X는 public language/content signal check,\nwebsite/app은 product explanation과 lightweight action path",
    include: ["Pre-launch", "Launch", "Post-launch", "Review", "Iteration"],
    slots: [
      "X: public language and content signal check",
      "Website/App: product explanation and lightweight action path",
      "Direct replies / outreach: qualitative message clarity check only",
      "Private evidence: 원문/handle/account ID 제외",
    ],
    process: ["Problem hook", "Visual test", "Page / response CTA", "Response review", "Message iteration", "Direction adjustment"],
  },
  {
    no: 23,
    section: "AHEYA",
    title: "Funnel & Landing",
    label: "Activation",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaLandingCallout",
    intent: "제품 설명 흐름 안에서 content discovery와 backing intent를 연결한다.",
    claim: "content discovery -> public idea page -> small response path -> response record",
    include: ["Content discovery", "Landing", "Project understanding", "CTA", "Backing intent"],
    slots: [
      "Discovery: X/content에서 문제 훅을 먼저 접함",
      "Landing: hero -> problem -> loop -> response record -> CTA",
      "Action: site visit과 backing intent를 별도 event로 분리",
      "Boundary: 측정 구조이지 성과 숫자가 아님",
    ],
    media: { src: "/aheya/aheyabaraya-homepage-2026-04-28.png", alt: "AHEYA homepage screenshot", label: "Landing surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
    ],
  },
  {
    no: 24,
    section: "AHEYA",
    title: "Content Strategy",
    label: "Content Strategy",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaContentAssetGrid",
    intent: "wallet/onchain mechanics보다 useful thing과 visual hook을 먼저 보여주는 전략을 정리한다.",
    claim: "콘텐츠 자산은 product outcome evidence가 아니라,\n복잡한 제품을 발견하게 만드는 visual discovery hook으로 사용",
    include: ["Problem hook", "Useful idea surface", "Founder first-response", "Visual/media hook"],
    slots: [
      "Purpose: abstract product를 더 쉽게 발견하게 만드는 visual hook",
      "Entry: visual interest에서 public idea page로 이동시키는 첫 touchpoint",
      "Memory: 반복 가능한 mood/character asset으로 기억 가능성 확보",
      "Boundary: visual assets are discovery assets, not product outcome evidence",
    ],
    gallery: [
      {
        src: "/aheya/worldbuilding/zodiac/aheya-tiger.webp",
        alt: "AHEYA zodiac tiger visual asset",
        label: "Zodiac",
        caption: "Will / resolve motif",
      },
      {
        src: "/aheya/worldbuilding/zodiac/aheya-cow.webp",
        alt: "AHEYA zodiac cow visual asset",
        label: "Zodiac set",
        caption: "repeatable visual system",
      },
      {
        src: "/aheya/worldbuilding/greek/aheya-athena-img.webp",
        alt: "AHEYA Athena visual asset",
        label: "Greek",
        caption: "Wisdom / response motif",
      },
      {
        src: "/aheya/worldbuilding/aheyacharacter/aheya-aheyabaraya-aurora.webp",
        alt: "AHEYA Aurora character visual asset",
        label: "Character",
        caption: "brand-memory asset",
      },
    ],
  },
  {
    no: 25,
    section: "AHEYA",
    title: "X Content Execution",
    label: "Execution",
    accent: "amber",
    variant: "evidence",
    custom: "aheyaXPostGrid",
    intent: "X post를 performance가 아니라 public copy와 product entry iteration ledger로 보여준다.",
    claim: "X posting은 product entry 변경 흐름과 함께 읽는다:\nlighter CTA, clearer first action, delayed Web3 mechanics",
    include: ["First response", "Response language", "Start from zero"],
    slots: [
      "Phase 1: link/testnet CTA -> product mention",
      "Phase 2: first users / first feedback problem -> builder outcome",
      "Phase 3: cleaner response / live demo / response record -> lighter product entry",
      "Product update: Web3 mechanics moved behind the first layer",
    ],
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-17.png",
        alt: "AHEYA public X post screenshot from 2026-03-17",
        label: "Strongest public post",
        href: "https://x.com/minnns_aheya/status/2033738008516825288",
        caption: "1,987 impressions / qualitative signal",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-27.png",
        alt: "AHEYA public X post screenshot from 2026-03-27",
        label: "Cleaner response copy",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        caption: "small response / response-record language",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-04-10.png",
        alt: "AHEYA public X post screenshot from 2026-04-10",
        label: "Builder start copy",
        href: "https://x.com/minnns_aheya/status/2042684370486727146",
        caption: "from-zero builder framing",
      },
    ],
    links: [
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
    ],
  },
  {
    no: 26,
    section: "AHEYA",
    title: "Internal-to-Public Messaging",
    label: "Copy Translation",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaMessagingEvolution",
    intent: "internal narrowing과 public X copy evolution을 분리한다.",
    claim: "Public copy는 Web3 mechanism보다\nbuilder outcome과 첫 반응 문제를 먼저 말해야 한다",
    include: ["Internal planning", "Public X copy", "Mechanism", "Technical boundary"],
    slots: ["reward/quest/funding -> small response path", "link/testnet CTA -> first user response", "wallet/onchain -> behind main UX", "technical depth -> appendix"],
    table: {
      headers: ["Layer", "Before", "After"],
      rows: [
        ["Internal planning", "reward / quest / funding / token mechanics", "lightweight backing intent + quick feedback + response record"],
        ["Public X copy", "link CTA, testnet, product mention", "first user response, public idea page, small backing intent"],
        ["Mechanism", "Web3 mechanics-first explanation", "wallet/onchain layer kept behind the main UX"],
        ["Decision", "complex technical depth in main story", "appendix boundary"],
      ],
    },
  },
  {
    no: 27,
    section: "AHEYA",
    title: "Qualitative Message Check",
    label: "Message Fit",
    accent: "violet",
    variant: "evidence",
    custom: "aheyaOutreachGrid",
    intent: "public reply 기반 message clarity와 segment fit 확인을 private evidence와 분리한다.",
    claim: "Public replies were used only to check message clarity and segment fit.\nThey are not sales, product outcome, or partnership evidence.",
    include: ["Exploratory", "Relevant segment", "High-fit builder", "Privacy boundary"],
    slots: [
      "Exploratory message: vibe coding / AI agents 대상 small response path 제안",
      "Relevant segment message: AI-native creators working on tools, agents, games",
      "High-fit builder message: founder-first response system for live demos",
      "Boundary: private DM body, handle, account ID excluded",
    ],
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-12.png",
        alt: "AHEYA public reply screenshot from 2026-03-12",
        label: "Exploratory reply",
        href: "https://x.com/minnns_aheya/status/2032169351508639949",
        caption: "small response offer",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-19.png",
        alt: "AHEYA public reply screenshot from 2026-03-19",
        label: "Relevant segment reply",
        href: "https://x.com/minnns_aheya/status/2034680247053164585",
        caption: "AI-native creator segment",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-04-02.png",
        alt: "AHEYA public reply screenshot from 2026-04-02",
        label: "High-fit builder reply",
        href: "https://x.com/minnns_aheya/status/2039543700045656099",
        caption: "founder-first response",
      },
    ],
    links: [
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
  },
  {
    no: 28,
    section: "AHEYA",
    title: "Early Signals & Measurement Plan",
    label: "Signal Read",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaSignalSplit",
    intent: "actual signal과 measurement plan을 명확히 분리한다.",
    claim: "Current evidence와 next events를 분리해,\nKPI outcome/funnel outcome claim 없이 early signal만 읽는다.",
    include: ["Actual signals", "Designed metrics", "DB/KPI caution"],
    slots: ["Public X post surface", "Strongest post metric as attention signal", "Public product surface", "landing_visit / project_open / backing_start / feedback_submit / response_reviewed"],
    table: {
      headers: ["구분", "포함", "해석"],
      rows: [
        ["Actual", "public X post surface, keyword matches, representative post metrics", "content attention signal only"],
        ["Actual", "product surface, test/runtime aggregate, Drive/source map", "system-surface evidence"],
        ["Designed", "visit, open, backing start, backing status, feedback submitted, response reviewed", "next decision structure"],
        ["Boundary", "KPI/SQL, aggregate, funnel", "성과 숫자나 개선 수치로 쓰지 않음"],
      ],
    },
  },
  {
    no: 29,
    section: "AHEYA",
    title: "Decision & Learning",
    label: "Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionClose",
    intent: "AHEYA의 결론을 검증 성공이 아니라 방향 판단으로 정리한다.",
    claim: "AHEYA는 Web3 mechanism보다\n공개 아이디어와 가벼운 반응 경로를 먼저 보여주는 방향이 맞다",
    include: ["Continue", "Lower", "Separate", "Next"],
    slots: ["Product story became simpler", "Web3/onchain stayed behind the main UX", "Content discovery and product action were separated", "KPI/SQL stayed as measurement design"],
    table: {
      headers: ["What this shows", "Portfolio read", "Evidence boundary"],
      rows: [
        ["PM", "Narrowed a broad reward/quest/funding idea into a testable live-idea response loop.", "scope and decision trace, not outcome result"],
        ["GTM", "Moved from mechanics-first language to builder-outcome messaging.", "message clarity, not demand result"],
        ["Content", "Used visual and X content as discovery hooks.", "attention signal, not product outcome result"],
        ["Data", "Designed KPI/event/SQL structure without overstating performance.", "measurement design, not KPI outcome"],
      ],
    },
    media: { src: "/aheya/ppt/aheya-core-rail-flow.svg", alt: "AHEYA small response path recap", label: "Decision recap" },
  },
] satisfies Slide[];
