import type { Slide } from "../types";

export const aheyaSlides = [
  {
    no: 9,
    section: "AHEYA",
    title: "AHEYA Overview",
    label: "Flagship Case",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaOverview",
    intent: "AHEYA 프로젝트의 역할, 기간, 산출물, 본문/appendix 경계를 한 장에서 정리한다.",
    claim: "AHEYA는 초기 아이디어 페이지에서\nwallet support와 짧은 피드백을 받는 product / GTM / content validation case",
    include: ["Role", "Evidence", "Boundary", "Appendix"],
    slots: [
      "Role: product planning, GTM framing, content system, measurement design",
      "Main evidence: public page, support/feedback flow, X content, KPI/event design, decision log",
      "Boundary: 성과/전환 입증이 아니라 초기 제품, 메시지, 콘텐츠 검증 사례",
      "Appendix: technical verification details, Trust/API notes, smart contract notes",
    ],
    media: { src: "/aheya/aheyabaraya-homepage-2026-04-28.png", alt: "AHEYA public surface", label: "AHEYA public surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
    note: "Commercial outcome and demand claims are excluded.",
  },
  {
    no: 10,
    section: "AHEYA",
    title: "Scope Narrowing",
    label: "Context",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaTimeline",
    intent: "넓은 초기 제품 기획에서 AHEYA public response flow와 public X CTA로 좁혀진 흐름을 날짜순으로 보여준다.",
    claim: "smart contract 중심 기획을\nwallet support, feedback, direct-send verification 중심으로 좁힌 과정",
    include: ["Smart contract plan", "Support/feedback UX", "Privy wallet", "Offchain publish", "Direct-send verification"],
    slots: ["Smart contract plan", "Support box", "Privy wallet", "Offchain publish", "Direct-send verify"],
    table: {
      headers: ["시점", "변화", "포트폴리오 의미"],
      rows: [
        ["2025-12~01", "smart contract / Solana deploy까지 고려한 큰 온체인 기획", "제품 의미를 전부 contract에 묶으면 첫 사용 이해가 무거워짐"],
        ["2026-02", "support box와 Good / Improve feedback UX를 먼저 정리", "builder와 supporter가 이해할 최소 행동을 찾음"],
        ["2026-02~03", "support chain을 mainnet-ready로 만들고 Privy Google wallet을 추가", "wallet 진입 마찰을 낮추되 서버 세션 truth는 유지"],
        ["2026-03~04", "publish smart contract 기본 경로를 wallet-signed offchain receipt로 축소", "live idea는 빠르게 열고, support verification은 별도로 엄격히 유지"],
        ["2026-04", "direct-send verify, dust support, feedback decouple로 흐름을 단순화", "기술 설명보다 public idea -> support -> feedback을 먼저 보이게 함"],
      ],
    },
  },
  {
    no: 11,
    section: "AHEYA",
    title: "Research to Problem",
    label: "Research",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaResearchSolution",
    intent: "리서치 두 축을 Web3 user 문제와 AI-native builder 문제로 구조화한다.",
    claim: "잔여 온체인 자산 리서치와 AI-native builder 공개 이후 반응 문제를 각각 Web3 user problem과 builder problem으로 연결",
    include: ["Residual onchain asset research", "AI-native builder response research", "Problem framing"],
    slots: ["Web3 user problem", "AI-native builder problem"],
    table: {
      headers: ["Research", "Evidence notes", "Problem", "Problem notes", "Tags"],
      rows: [
        [
          "잔여 온체인 자산 리서치",
          "에어드랍·퀘스트·거래 이후 native gas token과 project token이 지갑에 남는 흐름 확인 | Solana token account·CloseAccount, Base/EVM ERC-20 transfer·holding 조회 방식 정리 | 소액 자산이 숨김·방치·정리 대상으로 남기 쉬운지 확인",
          "온체인 활동이 실제 효용으로 이어지지 않음",
          "작은 자산은 지갑 안에 남지만 다시 쓰기에는 금액·gas·chain·용도 장벽이 있음 | 문제 정의는 수익이 아니라 소액 참여와 피드백으로 전환 가능한 utility gap",
          "native gas token | project token | wallet remainder | utility gap",
        ],
        [
          "AI-native builder 공개 이후 반응 리서치",
          "AI로 demo, docs, GitHub, launch post를 만드는 속도는 빨라짐 | 공개 이후 X marketing 글은 첫 반응과 피드백을 끌어내는 포텐셜이 낮게 남기 쉬움 | 첫 반응과 업데이트 근거가 흩어지는 문제 확인",
          "빠른 제작 이후 X marketing 포텐셜이 낮음",
          "builder는 demo를 열 수 있지만 X post만으로는 누가 실제로 봤고 무엇을 개선해야 하는지 남기기 어려움 | 필요한 것은 reward 참여가 아니라 첫 반응과 feedback이 다시 public copy와 reply로 이어지는 loop",
          "AI-native builder | demo speed | X marketing | feedback loop",
        ],
      ],
    },
  },
  {
    no: 12,
    section: "AHEYA",
    title: "Builder x Web3 Bridge",
    label: "Bridge",
    accent: "cyan",
    variant: "process",
    custom: "aheyaCoreRail",
    intent: "AI-native builder의 빠른 제작 문제와 Web3 user의 참여 행동 양식을 AHEYA 제품 구조로 연결한다.",
    claim: "AI-native builder의 빠른 제작 이후 문제에 Web3 user의 참여 행동을 붙여 support와 X feedback loop를 만드는 구조",
    include: ["Builder problem", "Web3 action", "AHEYABARAYA page", "X feedback loop"],
    slots: [
      "AI로 demo/service 제작 속도는 빨라졌지만 공개 이후 첫 반응과 피드백은 약함",
      "Web3 user의 visit/support/feedback/share 행동을 lightweight action으로 재해석",
      "feedback을 quote/reply 표면으로 다시 꺼내 초기 노출 가능성을 만듦",
      "exposure 가능성 설계이지 growth outcome claim은 아님",
    ],
    process: ["AI demo/service", "Live idea page", "Wallet support", "Quick feedback", "X quote/reply loop"],
    table: {
      headers: ["Layer", "Point", "Role"],
      rows: [
        [
          "AI-native builder",
          "demo/service 제작 속도는 빨라짐",
          "하지만 공개 이후 X 글만으로는 첫 반응과 명확한 피드백을 만들기 어렵다",
        ],
        [
          "Web3 user behavior",
          "visit, support, feedback, share 행동 양식",
          "Galxe식 참여 습관을 reward claim이 아니라 lightweight support / response로 재해석한다",
        ],
        [
          "Open",
          "AHEYABARAYA에 live idea를 올림",
          "builder의 demo를 설명 가능한 public page와 CTA 표면으로 바꾼다",
        ],
        [
          "Support",
          "wallet support로 첫 행동을 남김",
          "무거운 contract 설명보다 작은 support action으로 참여 장벽을 낮춘다",
        ],
        [
          "Feedback",
          "Good/Improve feedback을 X quote / reply 재료로 전환",
          "피드백을 public copy와 reply로 다시 꺼내 초기 제품 노출 가능성을 만든다",
        ],
      ],
    },
  },
  {
    no: 12.1,
    section: "AHEYA",
    title: "Builder Motion",
    label: "Product Map 12-1",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaProductSurfaceMap",
    intent: "builder가 live idea를 공개하고 feedback/record를 확인하는 흐름을 분리해서 보여준다.",
    claim: "Builder는 live idea를 열고,\n첫 support와 feedback을 다음 업데이트 판단 재료로 본다",
    include: ["Builder motion", "Idea page", "Feedback record", "Boundary"],
    slots: [
      "Builder: public idea page에서 live idea를 공유",
      "Problem: 빠르게 만든 demo가 첫 사용자와 명확한 피드백으로 이어지지 않음",
      "System: feedback and saved record layer에서 반응을 검토",
      "Boundary: builder-side review flow evidence이지 growth outcome evidence가 아님",
    ],
    gallery: [
      {
        src: "/aheya/aheya-corerail-creator.mp4",
        alt: "AHEYA builder-side response review video",
        label: "Builder review flow",
        type: "video",
        poster: "/aheya/aheya-lane-panels.webp",
        startTime: 1,
        caption: "feedback and saved record review",
      },
    ],
  },
  {
    no: 12.2,
    section: "AHEYA",
    title: "Web3 User Motion",
    label: "Product Map 12-2",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaProductSurfaceMap",
    intent: "Web3 user가 useful live idea를 열고 wallet support와 Good/Improve를 남기는 흐름을 분리해서 보여준다.",
    claim: "Web3 user는 온체인 활동을\n실제로 열어본 제품의 support와 Good/Improve 신호로 바꾼다",
    include: ["Web3 user motion", "Support action", "Quick feedback", "Boundary"],
    slots: [
      "User: useful live idea를 열고 실제로 써볼 대상을 확인",
      "Action: wallet으로 support하고 Good / Improve 중 하나를 남김",
      "System: support verification과 saved feedback record를 분리",
      "Boundary: utility/action design evidence이지 user demand proof가 아님",
    ],
    gallery: [
      {
        src: "/aheya/corerail-support-vid.mp4",
        alt: "AHEYA Web3 user support and feedback flow video",
        label: "Web3 user action flow",
        type: "video",
        poster: "/aheya/aheya-home-hero.webp",
        startTime: 1,
        caption: "open idea -> support from wallet -> Good / Improve",
      },
    ],
  },
  {
    no: 13,
    section: "AHEYA",
    title: "Screen Evidence Map",
    label: "Flow Evidence",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFeatureEvidenceMap",
    intent: "정적 화면 캡처를 기능별로 매칭해 어떤 화면이 어떤 product function을 맡는지 보여준다.",
    claim: "화면 캡처는 public idea, explore, action, record가\n어디에 구현되어 있는지 분리해서 보여준다",
    include: ["Public idea", "Explore", "Action", "Record"],
    slots: [
      "Public idea page: builder가 idea/project surface를 여는 화면",
      "Explore surface: builder entry와 discovery surface",
      "Action surface: early user가 wallet support와 quick feedback을 남기는 화면",
      "Feedback record: 이후 업데이트 판단에 참고할 수 있는 기록",
    ],
    gallery: [
      {
        src: "/aheya/page-assets/screens/aheya-aheya-mainpage.webp",
        alt: "AHEYA public idea page screenshot",
        label: "Public idea",
        caption: "builder가 여는 idea/project surface",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-explore.webp",
        alt: "AHEYA explore screenshot",
        label: "Explore",
        caption: "builder discovery surface",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-apppage.webp",
        alt: "AHEYA app page action screenshot",
        label: "Action page",
        caption: "wallet support and feedback action surface",
      },
      {
        src: "/aheya/aheya-lane-panels.webp",
        alt: "AHEYA saved feedback record lane panels",
        label: "Feedback record",
        caption: "saved feedback fields",
      },
    ],
  },
  {
    no: 14,
    section: "AHEYA",
    title: "First Target Hypothesis",
    label: "Prioritization",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionCards",
    intent: "Prioritization & Goals와 Hypotheses를 crypto/wallet-adjacent live-demo builder entry 중심으로 한 장에 묶는다.",
    claim: "첫 대상은 모든 Web3 사용자가 아니라,\nlive demo는 있지만 첫 사용자와 명확한 피드백이 부족한 AI-native builder",
    include: ["Live-demo builder", "First offer", "Minimal flow", "Measurement goal"],
    slots: ["AI-native builder first", "Outcome before full mechanism", "Wallet support as first action", "Reward/technical depth postponed"],
    table: {
      headers: ["우선순위", "선택", "이유"],
      rows: [
        ["Target", "AI-native builder with live demo, project page, GitHub, or launch post", "첫 사용자, 명확한 피드백, response evidence가 부족한 segment를 1차 대상으로 둔다."],
        ["Offer", "Public idea page where early users can explore, support from wallet, and leave quick feedback", "wallet action을 제거하지 않고 첫 참여 행동으로 단순화한다."],
        ["MVP flow", "public idea page, wallet-based support intent, quick feedback, saved feedback record", "처음 보는 사람도 이해할 수 있는 가장 작은 Web3 참여 행동만 남긴다."],
        ["Measurement", "content discovery, page open, wallet support, feedback, record event를 분리", "관찰한 반응과 다음 측정 가정을 분리해서 판단한다."],
      ],
    },
  },
  {
    no: 15,
    section: "AHEYA",
    title: "Product Direction",
    label: "Product Strategy",
    accent: "aqua",
    variant: "process",
    custom: "aheyaCoreRail",
    intent: "AHEYA의 현재 본문 제품 구조를 외부 사용자가 보는 흐름으로 고정한다.",
    claim: "public idea page -> wallet support -> quick Good/Improve feedback\n-> saved feedback record",
    include: ["Idea page", "Wallet support", "Good/Improve", "Feedback record"],
    slots: ["Wallet-based support remains in the product flow", "Action-first explanation, not mechanism-first", "Technical verification details stay in appendix", "Flow evidence, not conversion claim"],
    process: ["Public idea page", "Wallet-based support intent", "Quick Good/Improve feedback", "Saved feedback record"],
  },
  {
    no: 16,
    section: "AHEYA",
    title: "User Journey & Flow",
    label: "Flow",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFlowHero",
    intent: "SNS 발견부터 wallet support와 quick feedback까지의 짧은 경로를 보여준다.",
    claim: "X/content에서 public idea page로 들어와\nwallet-based support action과 quick feedback으로 이어지는 흐름",
    include: ["See", "Open", "Understand", "Support", "Feedback", "Record"],
    slots: [
      "첫 touchpoint는 X/content 또는 demo note",
      "project page에서 idea와 action path를 이해",
      "wallet support와 Good/Improve feedback은 saved feedback record로 남김",
      "flow evidence이지 funnel outcome evidence가 아님",
      "technical verification details stay in appendix",
    ],
    process: ["Discover", "Open", "Act", "Respond", "Record"],
    gallery: [
      {
        src: "/aheya/ppt/aheya-builder-flow-diagram.svg",
        alt: "AHEYA builder journey diagram",
        label: "Builder flow",
        caption: "live idea를 열고 support/feedback을 X feedback loop로 다시 꺼내는 흐름",
      },
      {
        src: "/aheya/ppt/aheya-backer-flow-diagram.svg",
        alt: "AHEYA backer supporter journey diagram",
        label: "Backer / supporter flow",
        caption: "idea를 보고 wallet support와 Good/Improve feedback을 남기는 흐름",
      },
    ],
  },
  {
    no: 17,
    section: "AHEYA",
    title: "MVP Scope",
    label: "Scope Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMvpCut",
    intent: "Included / Excluded Features와 Feature Prioritization을 명확히 분리한다.",
    claim: "builder entry와 first response에 필요한 것만 남기고\nreward-first framing과 technical depth는 뒤로 뺐다",
    include: ["Included", "Excluded", "Priority", "Boundary"],
    slots: ["Builder-facing idea surface", "Wallet support + quick feedback", "Saved feedback record + event hooks", "Reward/technical depth deferred"],
    table: {
      headers: ["Cut line", "MVP에 남긴 것", "판단 기준"],
      rows: [
        ["Included", "public idea page, project surface, builder problem hook", "builder가 support/feedback flow에 들어오는 입구"],
        ["Included", "wallet-based support action, quick Good/Improve feedback, saved feedback record", "wallet support와 피드백이 첫 observed response로 남는 최소 행동"],
        ["Priority", "KPI/event hooks, review list, saved feedback record", "재사용 가능한 response evidence와 다음 판단 구조"],
        ["Sequencing", "manual sourcing -> response sprint -> weekly review -> next lane decision", "12주 계획은 성과 예측이 아니라 운영 리듬과 학습 단위로 사용"],
        ["Deferred", "reward-first public framing, token launch, technical verification as front-door story, heavy automation", "첫 entry clarity를 흐리는 요소 제거"],
      ],
    },
  },
  {
    no: 18,
    section: "AHEYA",
    title: "Documentation & Decision Trace",
    label: "PM Artifacts",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaPlanningBoard",
    intent: "PRD, user stories, wireframe, roadmap, GTM, KPI, decision log를 실행 메모리로 연결한다.",
    claim: "원문 발췌와 판단 연결을 한 장에 묶은 planning evidence board",
    include: ["PRD", "User Stories", "Wireframe", "Roadmap", "KPI/SQL", "Decision log"],
    slots: ["AI-assisted planning", "Planning background", "Drive source map", "Read/not-reviewed boundary"],
    media: { src: "/aheya/ppt/aheya-document-decision-evidence-board.svg", alt: "AHEYA source excerpt and decision evidence board", label: "Sanitized source excerpt board" },
    table: {
      headers: ["Artifact", "Purpose", "Evidence cue", "Used for", "Boundary"],
      rows: [
        ["BP / Problem Thesis", "problem definition", "2026-03~04 BP/problem memo: reward-loop participation + builder growth gap cue", "problem slide and target hypothesis", "current commitment 아님"],
        ["Marketing / Ops Docs", "target and GTM", "2026-03 strategy notes: wallet-adjacent front door + reply/DM workflow cue", "GTM bridge and message ladder", "sales/partnership result claim 금지"],
        ["Flow / Code Map", "product flow", "2026-04 flow/code map: public idea, wallet support, feedback, saved record cue", "screen evidence and user flow", "raw code screenshot 제외"],
        ["KPI / SQL Notes", "measurement design", "KPI/SQL addendum: content, page, wallet support, feedback event split cue", "measurement board and signal read", "read-only snapshot 전 숫자 제한"],
        ["Decision Log / Handoff", "PM judgment", "handoff/decision log: keep, defer, appendix boundary cue", "scope cut and final learning", "인과 과장 금지"],
      ],
    },
  },
  {
    no: 19.1,
    section: "AHEYA",
    title: "Measurement Architecture",
    label: "KPI / SQL 19-1",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "KPI/SQL을 성과 숫자가 아니라 다음 판단을 위한 tracking architecture로 분리한다.",
    claim: "KPI는 성과 증명이 아니라 콘텐츠 발견부터 feedback record까지 어떤 이벤트를 볼지 정한 설계",
    include: ["KPI tree", "Event split", "Decision use", "Boundary"],
    slots: [
      "Tree: discovery -> entry -> wallet support -> quick feedback -> saved record",
      "Decision: 어디에서 drop되는지가 아니라 다음에 무엇을 더 명확히 설명할지 판단",
      "SQL: content/page/action/feedback 단위로 나눠 query-ready 구조를 준비",
      "Boundary: KPI outcome, conversion lift, market validation claim 아님",
    ],
  },
  {
    no: 19.2,
    section: "AHEYA",
    title: "Discovery Source Map",
    label: "KPI / SQL 19-2",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "X/content surface와 landing source를 측정 가능한 discovery source로 분리한다.",
    claim: "Discovery는 X post, visual hook, reply surface를 performance가 아니라 다음 content 판단 근거로 기록",
    include: ["Post URL", "Date", "Phase", "Content hook"],
    slots: [
      "Source: public X post surface와 visual hook을 content source로 분리",
      "Field: post URL, date, phase, asset type, message hook을 남김",
      "Use: 어떤 hook을 다음 content에 남길지 판단",
      "Boundary: impression 숫자는 attention cue이지 product outcome 아님",
    ],
  },
  {
    no: 19.3,
    section: "AHEYA",
    title: "Product Entry Events",
    label: "KPI / SQL 19-3",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "landing_visit, project_open, CTA click을 content 관심과 product 이해의 분리 이벤트로 보여준다.",
    claim: "Product entry는 content 관심과 제품 이해를 분리해 page open과 action intent를 따로 읽도록 설계",
    include: ["Landing visit", "Project open", "CTA click", "Session boundary"],
    slots: [
      "Entry: landing_visit과 project_open을 분리해 public page 이해 여부를 확인",
      "CTA: wallet support 전 단계의 support intent를 별도 이벤트로 둠",
      "Session: source, page, idea id, session id를 query key로 사용",
      "Boundary: 방문자 수가 아니라 다음 설명/CTA 수정 질문을 준비",
    ],
  },
  {
    no: 19.4,
    section: "AHEYA",
    title: "Support & Feedback Events",
    label: "KPI / SQL 19-4",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "wallet support와 quick feedback이 어떤 이벤트와 record로 남는지 보여준다.",
    claim: "Wallet support와 quick feedback은 한 덩어리가 아니라 intent, verification, feedback, saved record로 나눠 읽는다",
    include: ["Support start", "Support submit", "Feedback submit", "Record created"],
    slots: [
      "Support: wallet_support_start와 support_submit을 분리해 의도와 완료를 구분",
      "Feedback: Good/Improve와 freeform note는 saved feedback record로 남김",
      "Review: record_created 이후 review status를 다음 업데이트 판단에 사용",
      "Boundary: support 수량보다 reusable response evidence 구조가 핵심",
    ],
  },
  {
    no: 19.5,
    section: "AHEYA",
    title: "SQL Decision View",
    label: "KPI / SQL 19-5",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "SQL-ready event split을 다음 decision question으로 연결한다.",
    claim: "SQL은 성과를 증명하기 위한 숫자판이 아니라 다음 product/content decision을 묻기 위한 read model",
    include: ["Aggregate", "Filter", "Decision question", "Boundary"],
    slots: [
      "Aggregate: content/page/support/feedback 단위 COUNT와 FILTER를 준비",
      "Question: 어떤 source와 CTA가 support intent 또는 feedback record로 이어졌는지 확인",
      "Decision: message, visual hook, landing CTA, support UX를 다음 iteration 후보로 분리",
      "Boundary: read-only snapshot 전에는 final number, improvement claim을 쓰지 않음",
    ],
  },
  {
    no: 20,
    section: "AHEYA",
    title: "GTM Strategy",
    label: "GTM",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaGtmBridge",
    intent: "builder와 wallet-adjacent user를 Web3 mechanism이 아니라 first-response 문제로 연결하는 GTM bridge를 보여준다.",
    claim: "Full Web3 mechanism보다 builder problem을 먼저 말하고,\nwallet support는 lightweight user action으로 제안",
    include: ["Who", "Trigger", "Offer", "Bridge"],
    slots: ["Primary ICP: AI-native builder", "Secondary audience: Web3-curious user", "Offer: support and feedback path", "Outcome before full mechanism"],
    table: {
      headers: ["GTM element", "정의", "표현 원칙"],
      rows: [
        ["Primary ICP", "AI-native builder with a live demo or project page", "manual audience discovery 가능한 범위로 좁힘"],
        ["Trigger", "live demo 이후 first users / feedback / saved feedback record가 약함", "builder pain을 먼저 말함"],
        ["Offer", "explore the idea, support from wallet, leave quick feedback", "wallet support를 product action으로 설명"],
        ["Secondary audience", "Web3-curious users who can take a lightweight wallet-based support action", "token/contract보다 first user response로 끌어옴"],
      ],
    },
  },
  {
    no: 21,
    section: "AHEYA",
    title: "Messaging Framework",
    label: "Message",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMessageLadder",
    intent: "cold/warm/hot 접근 단계별로 내부 mechanism을 외부 메시지로 바꾼다.",
    claim: "Build는 빨라졌지만,\n첫 사용자 반응과 명확한 피드백은 여전히 느리다",
    include: ["Problem", "Offer", "Action", "Boundary"],
    slots: ["Problem: first user response is still slow", "Offer: live demo -> support and feedback path", "Action: open, support, leave feedback", "Boundary: reward thesis를 public test처럼 쓰지 않음"],
    table: {
      headers: ["Message layer", "Copy direction", "주의점"],
      rows: [
        ["Problem", "Build는 빨라졌지만 첫 반응은 여전히 느림", "성과를 약속하지 않음"],
        ["Open", "Open a live idea.", "수요 입증 표현 금지"],
        ["Support", "Support from wallet when it feels real.", "product action과 public page copy 정합"],
        ["Feedback", "Leave one clear Good/Improve feedback.", "market demand나 funnel performance claim 아님"],
        ["Boundary", "This does not claim market demand or funnel performance.", "reward-first quest 문장으로 쓰지 않음"],
      ],
    },
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-19.png",
        alt: "AHEYA public reply screenshot used as segment messaging evidence",
        label: "Segment reply evidence",
        href: "https://x.com/minnns_aheya/status/2034680247053164585",
        caption: "AI-native creator segment wording",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-27.png",
        alt: "AHEYA public X post screenshot used as messaging evidence",
        label: "Public copy evidence",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        caption: "first-response / saved feedback record public copy cue",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-04-10.png",
        alt: "AHEYA public X post screenshot used as later builder-start messaging evidence",
        label: "Late copy phase",
        href: "https://x.com/minnns_aheya/status/2042684370486727146",
        caption: "from-zero builder framing",
      },
    ],
  },
  {
    no: 22,
    section: "AHEYA",
    title: "Channel Test Plan",
    label: "Launch",
    accent: "violet",
    variant: "process",
    custom: "aheyaLaunchLoop",
    intent: "X, website/app, direct replies를 launch 성과가 아니라 language/content test surface로 분리한다.",
    claim: "X는 public language/content signal check,\nwebsite/app은 product explanation과 support/feedback action path",
    include: ["Pre-launch", "Launch", "Post-launch", "Review", "Iteration"],
    slots: [
      "X: public language and content signal check",
      "Website/App: product explanation and support/feedback action path",
      "Direct replies / outreach: qualitative message clarity check only",
      "Private evidence: 원문/handle/account ID 제외",
    ],
    process: ["Problem hook", "Visual test", "Page / response CTA", "Response review", "Message iteration", "Direction adjustment"],
  },
  {
    no: 23,
    section: "AHEYA",
    title: "Entry Flow & Landing",
    label: "Activation",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaLandingCallout",
    intent: "성과 funnel이 아니라 content discovery에서 wallet support와 quick feedback까지의 user entry flow를 보여준다.",
    claim: "content discovery -> public idea page -> wallet support\n-> quick feedback -> saved feedback record",
    include: ["Content discovery", "Landing", "Project understanding", "CTA", "Wallet support"],
    slots: [
      "Discovery: X/content에서 문제 훅을 먼저 접함",
      "Landing: hero -> problem -> loop -> saved feedback record -> CTA",
      "Action: site visit과 wallet support intent를 별도 event로 분리",
      "Boundary: entry-flow design이지 conversion funnel result가 아님",
    ],
    media: { src: "/aheya/page-assets/screens/aheya-aheya-mainpage.webp", alt: "AHEYA homepage screenshot", label: "Landing surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
    ],
  },
  {
    no: 24,
    section: "AHEYA",
    title: "Content Strategy",
    label: "Content Strategy",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaContentAssetGrid",
    intent: "wallet/onchain mechanics보다 useful thing과 visual hook을 먼저 보여주는 전략을 정리한다.",
    claim: "콘텐츠 자산은 product outcome evidence가 아니라,\n복잡한 제품을 발견하게 만드는 visual discovery hook으로 사용",
    include: ["Visual hook", "Repeatable mood", "Public entry", "Boundary"],
    slots: [
      "Purpose: abstract product를 더 쉽게 발견하게 만드는 visual hook",
      "Entry: visual interest에서 public idea page로 이동시키는 첫 touchpoint",
      "Memory: 반복 가능한 mood/character asset으로 기억 가능성 확보",
      "Boundary: visual assets are discovery assets, not product outcome evidence",
    ],
    gallery: [
      {
        src: "/aheya/worldbuilding/zodiac/aheya-tiger.webp",
        alt: "AHEYA zodiac tiger visual asset",
        label: "Visual hook",
        caption: "Will / resolve motif",
      },
      {
        src: "/aheya/worldbuilding/zodiac/aheya-cow.webp",
        alt: "AHEYA zodiac cow visual asset",
        label: "Repeatable mood",
        caption: "repeatable visual system",
      },
      {
        src: "/aheya/worldbuilding/greek/aheya-athena-img.webp",
        alt: "AHEYA Athena visual asset",
        label: "Signal motif",
        caption: "Wisdom / response motif",
      },
      {
        src: "/aheya/worldbuilding/aheyacharacter/aheya-aheyabaraya-aurora.webp",
        alt: "AHEYA Aurora character visual asset",
        label: "Brand memory",
        caption: "brand-memory asset",
      },
    ],
  },
  {
    no: 25,
    section: "AHEYA",
    title: "X Content Execution",
    label: "Execution",
    accent: "amber",
    variant: "evidence",
    custom: "aheyaXPostGrid",
    intent: "X post를 performance가 아니라 public copy와 product entry iteration ledger로 보여준다.",
    claim: "X posting은 product entry 변경 흐름과 함께 읽는다:\nclearer first action, wallet support, quick feedback",
    include: ["First response", "Response language", "Start from zero"],
    slots: [
      "Phase 1: link/testnet CTA -> product mention",
      "Phase 2: first users / first feedback problem -> builder outcome",
      "Phase 3: support from wallet + Good/Improve feedback -> clearer product entry",
      "Product update: technical verification details moved to appendix",
    ],
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-17.svg",
        alt: "AHEYA public X post screenshot from 2026-03-17",
        label: "Strongest public post",
        href: "https://x.com/minnns_aheya/status/2033738008516825288",
        caption: "1,987 impressions / qualitative signal",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-27.svg",
        alt: "AHEYA public X post screenshot from 2026-03-27",
        label: "Cleaner response copy",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        caption: "support/feedback language",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-04-10.svg",
        alt: "AHEYA public X post screenshot from 2026-04-10",
        label: "Builder start copy",
        href: "https://x.com/minnns_aheya/status/2042684370486727146",
        caption: "from-zero builder framing",
      },
    ],
    links: [
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
    ],
  },
  {
    no: 26,
    section: "AHEYA",
    title: "Internal-to-Public Messaging",
    label: "Copy Translation",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaMessagingEvolution",
    intent: "internal narrowing과 public X copy evolution을 분리한다.",
    claim: "Public copy는 기술 구조보다\nlive idea, wallet support, quick feedback 행동을 먼저 말해야 한다",
    include: ["Internal planning", "Public X copy", "Mechanism", "Technical boundary"],
    slots: ["reward/quest/funding -> support/feedback path", "link/testnet CTA -> first user response", "wallet support remains in the product flow", "technical verification details -> appendix"],
    table: {
      headers: ["Layer", "Before", "After"],
      rows: [
        ["Internal planning", "reward / quest / funding / token mechanics", "wallet support + quick feedback + saved feedback record"],
        ["Public X copy", "link CTA, testnet, product mention", "first user response, public idea page, wallet support"],
        ["Mechanism", "technical structure-first explanation", "user action first: open idea, support from wallet, leave feedback"],
        ["Decision", "complex technical depth in main story", "appendix boundary"],
      ],
    },
  },
  {
    no: 27,
    section: "AHEYA",
    title: "Qualitative Message Check",
    label: "Message Fit",
    accent: "violet",
    variant: "evidence",
    custom: "aheyaOutreachGrid",
    intent: "public reply 기반 message clarity와 segment fit 확인을 private evidence와 분리한다.",
    claim: "Public replies were used only to check message clarity and segment fit.\nThey are not sales, product outcome, or partnership evidence.",
    include: ["Exploratory", "Relevant segment", "High-fit builder", "Privacy boundary"],
    slots: [
      "Exploratory message: vibe coding / AI agents 대상 support/feedback path 제안",
      "Relevant segment message: AI-native creators working on tools, agents, games",
      "High-fit builder message: founder-first response system for live demos",
      "Boundary: private DM body, handle, account ID excluded",
    ],
    gallery: [
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-12.png",
        alt: "AHEYA public reply screenshot from 2026-03-12",
        label: "Exploratory reply",
        href: "https://x.com/minnns_aheya/status/2032169351508639949",
        caption: "support/feedback offer",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-19.png",
        alt: "AHEYA public reply screenshot from 2026-03-19",
        label: "Relevant segment reply",
        href: "https://x.com/minnns_aheya/status/2034680247053164585",
        caption: "AI-native creator segment",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-04-02.png",
        alt: "AHEYA public reply screenshot from 2026-04-02",
        label: "High-fit builder reply",
        href: "https://x.com/minnns_aheya/status/2039543700045656099",
        caption: "founder-first response",
      },
    ],
    links: [
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
  },
  {
    no: 28,
    section: "AHEYA",
    title: "Pre-Decision Signal Review",
    label: "Signal Read",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaSignalSplit",
    intent: "앞단 X, product surface, KPI/SQL 설계를 결론 직전 판단 재료로 정리한다.",
    claim: "X 반응과 KPI 설계는 성과 입증이 아니라 다음 판단을 위한 signal review다.",
    include: ["X/content evidence", "Product surface", "KPI/SQL design", "Decision boundary"],
    slots: ["Public X post/reply evidence", "Landing and support/feedback surface", "Event/source mapping", "No outcome claim"],
    table: {
      headers: ["Source", "Signal read", "Decision use"],
      rows: [
        ["X / content", "public post, reply, representative post metric은 어떤 언어와 visual hook이 attention을 받는지 보는 표면", "content angle과 outreach wording을 조정하는 재료"],
        ["Product surface", "landing, project page, wallet support, quick feedback path는 첫 action이 가능한지 확인하는 구현 표면", "다음 MVP에서 남길 행동과 줄일 설명을 판단"],
        ["KPI / SQL design", "landing_visit, project_open, wallet_support_start, feedback_submit, feedback_record_created를 event/source로 분리", "성과 숫자가 아니라 이후 read-only snapshot의 기준선"],
        ["Boundary", "current deck에서는 conversion, market validation, KPI lift를 결론으로 쓰지 않음", "29번은 방향 판단과 다음 측정 구조로만 연결"],
      ],
    },
  },
  {
    no: 29,
    section: "AHEYA",
    title: "Decision & Learning",
    label: "Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionClose",
    intent: "AHEYA의 결론을 검증 성공이 아니라 방향 판단으로 정리한다.",
    claim: "AHEYA는 기술 구조보다\npublic idea, wallet support, quick feedback을 먼저 보여주는 방향이 맞다",
    include: ["Continue", "Lower", "Separate", "Next"],
    slots: ["Product story became simpler", "Wallet support remained as a visible product action", "Technical verification details moved to appendix", "KPI/SQL stayed as measurement design"],
    table: {
      headers: ["What this proves", "Portfolio read", "Evidence boundary"],
      rows: [
        ["PM", "Narrowed a broad reward/quest/funding idea into a visible idea/support/feedback flow.", "scope and decision trace, not outcome result"],
        ["GTM", "Moved from technical-structure-first language to builder-outcome messaging.", "message clarity, not demand result"],
        ["Content", "Used visual and X content as discovery hooks.", "attention signal, not product outcome result"],
        ["Data", "Designed KPI/event/SQL structure without overstating performance.", "measurement design, not KPI outcome"],
      ],
    },
    media: { src: "/aheya/ppt/aheya-core-rail-flow.svg", alt: "AHEYA support and feedback flow recap", label: "Decision recap" },
  },
] satisfies Slide[];
