import type { Slide } from "../types";

export const aheyaSlides = [
  {
    no: 9,
    section: "AHEYA",
    title: "AHEYA Overview",
    label: "Flagship Case",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaOverview",
    intent: "AHEYA 프로젝트의 역할, 기간, 산출물, 본문/appendix 경계를 한 장에서 정리한다.",
    claim: "AHEYA는 AI service idea를 공개하고 암호화폐 소액 후원과 Good/Improve 상세 피드백을 받는 product / GTM / content validation case",
    include: ["Role", "Evidence", "Boundary", "Appendix"],
    slots: [
      "Role: product planning, GTM framing, content system, measurement design",
      "Main evidence: public page, small crypto donation, Good/Improve feedback, Share on X, KPI/event design",
      "Boundary: 성과/전환 입증이 아니라 초기 제품, 메시지, 콘텐츠 검증 사례",
      "Appendix: technical verification, API notes, smart contract notes",
    ],
    media: { src: "/aheya/aheyabaraya-homepage-2026-04-28.png", alt: "AHEYA public surface", label: "AHEYA public surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
    note: "성과/전환 입증이 아니라 초기 제품, 메시지, 콘텐츠 검증 사례.",
  },
  {
    no: 10,
    section: "AHEYA",
    title: "Scope Narrowing",
    label: "Context",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaTimeline",
    intent: "넓은 초기 제품 기획에서 AHEYA public response flow와 public X CTA로 좁혀진 흐름을 날짜순으로 보여준다.",
    claim: "smart contract 중심 기획을 소액 후원, Good/Improve 피드백, direct-send verification 중심으로 좁힌 과정",
    include: ["Smart contract plan", "Donation/feedback UX", "Privy wallet", "Offchain publish", "Direct-send verification"],
    slots: ["Smart contract plan", "Donation box", "Privy wallet", "Offchain publish", "Direct-send verify"],
    table: {
      headers: ["시점", "변화", "포트폴리오 의미"],
      rows: [
        ["2025-12~01", "Smart contract / Solana deploy까지 고려한 큰 온체인 기획", ""],
        ["2026-02", "소액 후원 + Good/Improve UX로 첫 행동을 좁힘", ""],
        ["2026-02~03", "Mainnet-ready 후원 flow + Privy wallet entry 정리", ""],
        ["2026-03~04", "Public idea와 wallet-signed receipt로 설명 축소", ""],
        ["2026-04", "Direct-send verify와 feedback record를 분리", ""],
      ],
    },
  },
  {
    no: 11,
    section: "AHEYA",
    title: "Research to Problem",
    label: "Research",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaResearchSolution",
    intent: "잔여 온체인 자산의 효용 부족과 AI builder의 첫 반응 확보 문제를 구조화한다.",
    claim: "Web3 user의 잔여 온체인 자산 문제와 AI builder의 공개 후 반응 확보 문제를 하나의 제품 과제로 연결",
    include: ["Residual onchain asset research", "AI-native builder response research", "Problem framing"],
    slots: ["Web3 user problem", "AI-native builder problem"],
    table: {
      headers: ["Research", "Evidence notes", "Problem", "Problem notes", "Tags"],
      rows: [
        [
          "잔여 온체인 자산 리서치",
          "에어드랍·퀘스트·거래 이후 지갑에 남는 native gas token / project token 잔여 흐름을 정리 | Solana token account와 CloseAccount 회수 구조, Base/EVM transfer history와 current holding 조회 방식을 비교 | 남은 금액·체인·용도가 실제 사용 행동으로 이어지기 어려운 이유를 관찰",
          "온체인 활동이 실제 효용으로 이어지지 않음",
          "작은 자산은 지갑 안에 남지만 다시 쓰기에는 금액·gas·chain·용도 장벽이 있음 | 문제 정의는 수익이 아니라 실제 효용 있는 서비스 경험으로 연결되기 어려운 utility gap",
          "native gas token | project token | wallet remainder | utility gap",
        ],
        [
          "AI-native builder 공개 이후 반응 리서치",
          "AI로 demo/service/tool/agent는 빠르게 만들 수 있지만 X에 올린 뒤 첫 반응과 상세 피드백을 얻기는 어려움 | 제품을 만든 이후에도 누가 실제로 봤고 무엇을 고쳐야 하는지 남기는 장치가 약함",
          "만들기는 쉬워졌지만 첫 반응과 피드백을 얻기는 여전히 어려운 상황",
          "builder는 demo를 빠르게 만들 수 있지만 X post만으로는 첫 사용자 반응과 개선 근거가 충분히 남지 않음 | 필요한 것은 reward 참여가 아니라 소액 후원, 상세 피드백, Share on X, saved feedback record를 연결하는 loop",
          "AI demo speed | product promotion | first response | feedback loop",
        ],
      ],
    },
  },
  {
    no: 12,
    section: "AHEYA",
    title: "Builder x Web3 Value Bridge",
    label: "Bridge",
    accent: "cyan",
    variant: "process",
    custom: "aheyaBuilderBridge",
    intent: "AI builder의 첫 반응 확보 문제와 Web3 user의 잔여 온체인 자산 효용 문제를 연결한다.",
    claim: "AI builder는 후원과 피드백 기록을 얻고, Web3 user는 잔여 온체인 자산을 AI service idea 후원으로 사용한다",
    include: ["Builder problem", "Small crypto donation", "AHEYABARAYA page", "Share on X"],
    slots: [
      "AI builder: 소액 후원, Good/Improve 상세 피드백, saved feedback record를 얻음",
      "Web3 user: 잔여 온체인 자산을 실제 효용 가능성이 있는 AI service idea에 후원",
      "AHEYABARAYA: feedback을 사용자 주도 Share on X와 내부 기록으로 분리",
      "X 노출 보장이 아니라 공개 반응이 생길 수 있는 UX 연결점",
    ],
    process: ["Original X post", "Public idea page", "Small crypto donation", "Detailed Good/Improve feedback", "Share on X", "Saved feedback record"],
    table: {
      headers: ["Layer", "Point", "Role"],
      rows: [
        [
          "AI-native builder",
          "빠르게 만든 demo",
          "원본 X 글에서 public idea page로 연결하고 소액 후원, 상세 피드백, saved feedback record를 다음 업데이트 재료로 얻음",
        ],
        [
          "Web3 user",
          "잔여 온체인 자산의 효용",
          "작은 온체인 자산을 실제 효용 가능성이 있는 AI service idea에 대한 후원으로 사용",
        ],
        [
          "Open",
          "Original X post",
          "builder가 demo/service/tool/agent를 소개하는 원본 X 글을 먼저 올림",
        ],
        [
          "Donation",
          "Small crypto donation",
          "무거운 contract 설명보다 암호화폐 소액 후원을 먼저 보여줌",
        ],
        [
          "Feedback loop",
          "Share on X + saved record",
          "상세 피드백을 사용자가 원할 때 공개 반응으로 연결하고 내부 기록에도 저장",
        ],
      ],
    },
  },
  {
    no: 12.1,
    section: "AHEYA",
    title: "Builder Motion",
    label: "Product Map 12-1",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaProductSurfaceMap",
    intent: "builder가 원본 X 글에서 AHEYA page로 연결하고 후원/피드백/공유 기록을 확인하는 흐름을 보여준다.",
    claim: "Builder는 원본 X 글을 anchor로 삼아 소액 후원, 상세 피드백, saved record를 다음 업데이트 판단 재료로 본다",
    include: ["Original X post", "Idea page", "Donation", "Saved record"],
    slots: [
      "Builder gets: 소액 후원 / 상세 피드백 / saved record",
      "Decision use: 다음 업데이트 판단 재료",
      "Content use: 사용자가 선택한 Share on X",
      "Boundary: X 노출 보장 아님",
    ],
    gallery: [
      {
        src: "/aheya/aheya-corerail-creator.mp4",
        alt: "AHEYA builder-side response review video",
        label: "Builder review flow",
        type: "video",
        poster: "/aheya/aheya-lane-panels.webp",
        startTime: 1,
        caption: "donation, detailed feedback, saved record review",
      },
    ],
  },
  {
    no: 12.2,
    section: "AHEYA",
    title: "Web3 User Motion",
    label: "Product Map 12-2",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaProductSurfaceMap",
    intent: "Web3 user가 잔여 온체인 자산을 실제 효용 가능성이 있는 AI service idea에 소액 후원하는 흐름을 보여준다.",
    claim: "Web3 user는 남은 온체인 자산을 암호화폐 소액 후원으로 사용하고 Good/Improve 상세 피드백을 남긴다",
    include: ["Residual asset", "Small donation", "Detailed feedback", "Share boundary"],
    slots: [
      "Web3 user gets: 남은 온체인 자산을 AI service idea에 사용",
      "Decision use: Good/Improve 상세 피드백",
      "System: Share on X와 saved feedback record 분리",
      "Boundary: demand proof 아님",
    ],
    gallery: [
      {
        src: "/aheya/corerail-support-vid.mp4",
        alt: "AHEYA Web3 user support and feedback flow video",
        label: "Web3 user action flow",
        type: "video",
        poster: "/aheya/aheya-home-hero.webp",
        startTime: 1,
        caption: "open idea -> small crypto donation -> Good/Improve feedback",
      },
    ],
  },
  {
    no: 13,
    section: "AHEYA",
    title: "Screen Evidence Map",
    label: "Flow Evidence",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFeatureEvidenceMap",
    intent: "정적 화면 캡처를 기능별로 연결해 어떤 화면이 어떤 기능을 맡는지 보여준다.",
    claim: "각 화면이 public idea, explore, 소액 후원, feedback record 기능을 어디에서 담당하는지 보여준다",
    include: ["Public idea", "Explore", "Action", "Record"],
    slots: [
      "Public idea page: 아이디어를 한 화면에서 이해하고 시작하는 공개 화면",
      "Explore surface: 다른 live idea를 탐색하는 진입 화면",
      "Action surface: 암호화폐 소액 후원과 Good/Improve를 남기는 행동 화면",
      "Feedback record: 다음 업데이트에 참고할 수 있는 saved feedback record",
    ],
    gallery: [
      {
        src: "/aheya/page-assets/screens/aheya-aheya-mainpage.webp",
        alt: "AHEYA public idea page screenshot",
        label: "Public idea",
        caption: "아이디어를 한 화면에서 이해하고 시작",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-explore.webp",
        alt: "AHEYA explore screenshot",
        label: "Explore",
        caption: "다른 live idea를 탐색하는 진입 화면",
      },
      {
        src: "/aheya/page-assets/screens/aheya-aheya-apppage.webp",
        alt: "AHEYA app page action screenshot",
        label: "Action page",
        caption: "소액 후원과 Good/Improve 행동 화면",
      },
      {
        src: "/aheya/aheya-lane-panels.webp",
        alt: "AHEYA saved feedback record lane panels",
        label: "Feedback record",
        caption: "다음 업데이트에 참고하는 saved feedback record",
      },
    ],
  },
  {
    no: 14,
    section: "AHEYA",
    title: "첫 타깃 가설",
    label: "우선순위",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionCards",
    intent: "첫 타깃, 첫 제안, 최소 행동, 측정 기준을 한 장에 묶는다.",
    claim: "첫 대상은 모든 Web3 사용자가 아니라 데모는 있지만 첫 사용자와 명확한 피드백이 부족한 AI builder",
    include: ["데모를 만든 builder", "첫 제안", "최소 행동", "측정 기준"],
    slots: ["AI builder 우선", "기술 설명보다 결과 먼저", "소액 후원을 첫 행동으로", "reward와 기술 설명은 뒤로"],
    table: {
      headers: ["우선순위", "선택", "이유"],
      rows: [
        ["대상", "라이브 데모를 만든 AI builder", "데모는 있지만 첫 사용자와 피드백이 부족함"],
        ["제안", "아이디어를 공개하고 암호화폐 소액 후원 받기", "기술 설명보다 첫 참여 행동을 먼저 보여줌"],
        ["행동", "상세 Good/Improve 피드백 남기기", "처음 보는 사람도 바로 남길 수 있는 반응"],
        ["측정", "방문, 후원, 피드백 기록을 분리해 측정하기", "성과가 아니라 다음 개선 판단을 위한 기준"],
      ],
    },
  },
  {
    no: 15,
    section: "AHEYA",
    title: "Product Direction",
    label: "Product Strategy",
    accent: "aqua",
    variant: "process",
    custom: "aheyaCoreRail",
    intent: "AHEYA의 현재 본문 제품 구조를 외부 사용자가 보는 흐름으로 고정한다.",
    claim: "original X post -> public idea page -> small crypto donation -> detailed feedback -> Share on X -> saved record",
    include: ["Original X post", "Idea page", "Donation", "Feedback", "Share on X", "Saved record"],
    slots: ["Original X post anchors the public idea", "Small crypto donation remains the lightweight action", "Share on X is user-led, not automated", "Flow evidence, not conversion claim"],
    process: ["Original X post", "Public idea page", "Small crypto donation", "Detailed Good/Improve", "Share on X", "Saved feedback record"],
  },
  {
    no: 16,
    section: "AHEYA",
    title: "User Journey & Flow",
    label: "Flow",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaFlowHero",
    intent: "원본 X 글에서 public idea page, 소액 후원, 상세 피드백, Share on X, saved record로 이어지는 경로를 보여준다.",
    claim: "X/content에서 public idea page로 들어와 암호화폐 소액 후원과 상세 Good/Improve 피드백으로 이어지는 흐름",
    include: ["X post", "Page", "Donation", "Feedback", "Share", "Record"],
    slots: [],
    process: ["Original X post", "Open page", "Donate", "Respond", "Share on X", "Save record"],
  },
  {
    no: 17,
    section: "AHEYA",
    title: "MVP Scope",
    label: "Scope Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMvpCut",
    intent: "Included / Excluded Features와 Feature Prioritization을 명확히 분리한다.",
    claim: "후원, 상세 피드백, Share on X에 필요한 최소 흐름만 남기고 reward-first framing과 technical depth는 보류했다",
    include: ["Included", "Excluded", "Priority", "Boundary"],
    slots: ["Builder-facing idea surface", "Small crypto donation + detailed feedback", "Saved feedback record + event hooks", "Reward/technical depth deferred"],
    table: {
      headers: ["Cut line", "MVP에 남긴 것", "판단 기준"],
      rows: [
        ["Included", "original X post anchor, public idea page, builder problem hook", "builder가 AHEYA page로 연결되는 입구"],
        ["Included", "small crypto donation, detailed Good/Improve feedback, saved feedback record", "후원과 피드백이 처음 관찰 가능한 반응으로 남는 최소 행동"],
        ["Included", "Share on X action point", "사용자가 선택할 때 공개 reply/quote 흐름으로 연결"],
        ["Priority", "KPI/event hooks, review list, saved feedback record", "재사용 가능한 response evidence와 다음 판단 구조"],
        ["Sequencing", "manual sourcing -> response sprint -> weekly review -> next lane decision", "12주 계획은 성과 예측이 아니라 운영 리듬과 학습 단위로 사용"],
        ["Deferred", "reward-first public framing, token launch, automated posting, technical verification as front-door story", "첫 entry clarity를 흐리거나 policy risk가 큰 요소 보류"],
      ],
    },
  },
  {
    no: 18,
    section: "AHEYA",
    title: "Documentation & Decision Trace",
    label: "PM Artifacts",
    accent: "violet",
    variant: "matrix",
    custom: "aheyaPlanningBoard",
    intent: "리서치, 기획, GTM, KPI, decision log를 제품 판단과 반영 근거로 연결한다.",
    claim: "원문 발췌와 판단 연결을 한 장에 묶어 리서치에서 제품 반영까지의 evidence trace를 보여준다",
    include: ["Research", "PRD", "GTM", "KPI/SQL", "Decision log", "Boundary"],
    slots: ["Trading-info supply-side", "InfoFi / X API risk", "AI builder pivot", "Share on X boundary"],
    media: { src: "/aheya/ppt/aheya-document-decision-evidence-board.svg", alt: "AHEYA source excerpt and decision evidence board", label: "Sanitized source excerpt board" },
    table: {
      headers: ["Artifact", "Purpose", "Evidence cue", "Used for", "Boundary"],
      rows: [
        ["Residual Asset Research", "problem definition", "native gas/project token 잔여 흐름과 Solana CloseAccount cue", "utility gap and small crypto donation thesis", "시장 전체 통계로 해석하지 않음"],
        ["Trading-info Planning", "initial supply-side", "crypto trading information sharing에서 crypto traders가 supply-side였던 기록", "AI builder pivot context", "현재 타깃으로 그대로 쓰지 않음"],
        ["InfoFi / X Risk Notes", "pivot rationale", "Kaito-like InfoFi / X API / reward-for-posting risk cue", "user-led Share on X boundary", "자동 포스팅 또는 보상형 X action 아님"],
        ["Flow / Code Map", "product flow", "2026-04 flow/code map: public idea, small donation, Good/Improve, saved record cue", "screen evidence and user flow", "raw code screenshot 제외"],
        ["KPI / SQL Notes", "measurement design", "content, page, donation, feedback, Share on X, saved record event split cue", "measurement board and signal read", "read-only snapshot 전 숫자 제한"],
        ["Decision Log / Handoff", "PM judgment", "handoff/decision log: keep, defer, appendix boundary cue", "scope cut and final learning", "인과 과장 금지"],
      ],
    },
  },
  {
    no: 19.1,
    section: "AHEYA",
    title: "Measurement Architecture",
    label: "KPI / SQL 19-1",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "KPI/SQL을 성과 숫자가 아니라 다음 판단을 위한 tracking architecture로 분리한다.",
    claim: "KPI는 성과 증명이 아니라 원본 X 글부터 후원, 피드백, Share on X, saved record까지 어떤 이벤트를 볼지 정한 설계",
    include: ["KPI tree", "Event split", "Decision use", "Boundary"],
    slots: [
      "Tree: original X post -> page entry -> small donation -> detailed feedback -> Share on X -> saved record",
      "Decision: 어디에서 이탈했는지가 아니라 다음에 무엇을 더 명확히 설명할지 판단",
      "SQL: content/page/donation/feedback/share/record 단위로 나눠 query-ready 구조를 준비",
      "Boundary: KPI output이 아니라 measurement design",
    ],
    media: { src: "/aheya/ppt/source-snips/aheya-19-1-kpi-ledger-source.html.png", alt: "KPI aggregate ledger source proof lines", label: "source line capture" },
  },
  {
    no: 19.2,
    section: "AHEYA",
    title: "Discovery Source Map",
    label: "KPI / SQL 19-2",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "X/content surface와 landing source를 측정 가능한 discovery source로 분리한다.",
    claim: "Discovery는 X post, visual hook, reply surface를 performance가 아니라 다음 content 판단 근거로 기록",
    include: ["Post URL", "Date", "Phase", "Content hook"],
    slots: [
      "Source: public X post surface와 visual hook을 content source로 분리",
      "Field: post URL, date, phase, asset type, message hook을 남김",
      "Use: 어떤 hook을 다음 content에 남길지 판단",
      "Boundary: impression 숫자는 attention cue이지 traction proof가 아님",
    ],
    media: { src: "/aheya/ppt/source-snips/aheya-19-2-x-ledger-source.html.png", alt: "X sanitized post ledger source proof lines", label: "source line capture" },
  },
  {
    no: 19.3,
    section: "AHEYA",
    title: "Product Entry Events",
    label: "KPI / SQL 19-3",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "site visit, project open, CTA click을 content 관심과 product 이해의 분리 이벤트로 보여준다.",
    claim: "Product entry는 원본 X 글, public idea page, 후원 intent를 분리해 읽도록 설계",
    include: ["Landing visit", "Project open", "CTA click", "Session boundary"],
    slots: [
      "Entry: original_x_post와 public idea page open을 분리해 이해 여부를 확인",
      "CTA: 소액 후원 전 단계의 donation intent를 별도 이벤트 후보로 둠",
      "Session: source, page, idea id, session id를 query key 후보로 사용",
      "Boundary: 방문자 수가 아니라 다음 설명/CTA 수정 질문을 준비",
    ],
    media: { src: "/aheya/ppt/source-snips/aheya-19-3-event-plan-source.html.png", alt: "KPI tree and entry event plan source proof lines", label: "source line capture" },
  },
  {
    no: 19.4,
    section: "AHEYA",
    title: "Donation & Feedback Events",
    label: "KPI / SQL 19-4",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "소액 후원과 상세 Good/Improve 피드백이 어떤 이벤트와 record로 남는지 보여준다.",
    claim: "소액 후원과 상세 피드백은 한 덩어리가 아니라 intent, verification, feedback, Share on X, saved record로 나눠 읽는다",
    include: ["Donation intent", "Donation submit", "Feedback submit", "Share on X", "Record created"],
    slots: [
      "Donation: donation_intent와 donation_submit을 분리해 의도와 완료를 구분",
      "Feedback: Good/Improve와 detailed note는 saved feedback record로 남김",
      "Share: Share on X는 user-led action 후보로 분리",
      "Review: record_created 이후 review status를 다음 업데이트 판단에 사용",
      "Boundary: 후원 수량보다 reusable response evidence 구조가 핵심",
    ],
    media: { src: "/aheya/ppt/source-snips/aheya-19-4-feedback-service-source.html.png", alt: "Feedback service source proof lines", label: "source line capture" },
  },
  {
    no: 19.5,
    section: "AHEYA",
    title: "SQL Decision View",
    label: "KPI / SQL 19-5",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaCsvEvidence",
    intent: "SQL-ready event split을 다음 decision question으로 연결한다.",
    claim: "SQL은 성과를 증명하기 위한 숫자판이 아니라 다음 product/content decision을 묻기 위한 read model",
    include: ["Aggregate", "Filter", "Decision question", "Boundary"],
    slots: [
      "Aggregate: content/page/donation/feedback/share/record 단위 COUNT와 FILTER를 준비",
      "Question: 어떤 source와 CTA가 donation intent 또는 feedback record로 이어졌는지 확인",
      "Decision: message, visual hook, landing CTA, donation UX를 다음 iteration 후보로 분리",
      "Boundary: read-only snapshot 전에는 final number, improvement claim을 쓰지 않음",
    ],
    media: { src: "/aheya/ppt/source-snips/aheya-19-5-kpi-export-source.html.png", alt: "KPI export source proof lines", label: "source line capture" },
  },
  {
    no: 20,
    section: "AHEYA",
    title: "GTM Strategy",
    label: "GTM",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaGtmBridge",
    intent: "builder의 첫 반응 확보 문제와 Web3 user의 잔여 온체인 자산 사용 문제를 GTM bridge로 연결한다.",
    claim: "전체 Web3 구조보다 builder problem을 먼저 말하고 암호화폐 소액 후원은 가벼운 user action으로 제안",
    include: ["Who", "Trigger", "Offer", "Bridge"],
    slots: ["Primary ICP: AI-native builder", "Secondary audience: Web3-curious user", "Offer: small donation and feedback path", "Outcome before full mechanism"],
    table: {
      headers: ["GTM element", "정의", "표현 원칙"],
      rows: [
        ["Primary ICP", "AI-native builder with a demo, service, tool, or agent idea", "manual audience discovery 가능한 범위로 좁힘"],
        ["Trigger", "빠르게 만든 demo 이후 첫 반응, 상세 피드백, saved feedback record가 부족함", "builder pain을 먼저 말함"],
        ["Offer", "open the idea, receive small crypto donations, collect detailed Good/Improve feedback", "후원을 product action으로 설명"],
        ["Secondary audience", "Web3-curious users with leftover onchain assets", "token/contract보다 useful idea 후원으로 끌어옴"],
      ],
    },
  },
  {
    no: 21,
    section: "AHEYA",
    title: "Messaging Framework",
    label: "Message",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaMessageLadder",
    intent: "cold/warm/hot 접근 단계별로 내부 mechanism을 외부 메시지로 바꾼다.",
    claim: "AI로 demo를 만드는 속도는 빨라졌지만 첫 반응과 명확한 피드백을 얻기는 여전히 어렵다",
    include: ["Problem", "Offer", "Donation", "Feedback", "Share", "Boundary"],
    slots: ["Problem: 첫 반응과 피드백 확보가 어렵다", "Offer: live demo -> donation and feedback path", "Action: open, donate, leave feedback", "Boundary: reward thesis를 public test처럼 쓰지 않음"],
    table: {
      headers: ["Message layer", "Copy direction", "주의점"],
      rows: [
        ["Problem", "AI로 demo를 만드는 속도는 빨라졌지만 첫 반응과 피드백을 얻기는 어렵다", ""],
        ["Open", "Open a live idea.", ""],
        ["Donation", "Make a small crypto donation.", ""],
        ["Feedback", "Leave detailed Good/Improve feedback.", ""],
        ["Share", "Share feedback on X when you choose.", ""],
        ["Boundary", "Validation design, not traction proof.", ""],
      ],
    },
    gallery: [
      {
        alt: "AHEYA public X embed used as builder messaging evidence",
        label: "Builder bottleneck post",
        href: "https://x.com/minnns_aheya/status/2037565714002059444",
        embedUrl: "https://x.com/minnns_aheya/status/2037565714002059444",
        embedType: "x",
        caption: "builder marketing bottleneck wording",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-03-27.png",
        alt: "AHEYA public X post screenshot used as messaging evidence",
        label: "Public copy evidence",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        caption: "first-response / saved feedback record public copy cue",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-x-post-2026-04-10.png",
        alt: "AHEYA public X post screenshot used as later builder-start messaging evidence",
        label: "Late copy phase",
        href: "https://x.com/minnns_aheya/status/2042684370486727146",
        caption: "from-zero builder framing",
      },
    ],
  },
  {
    no: 22,
    section: "AHEYA",
    title: "Channel Test Plan",
    label: "Launch",
    accent: "violet",
    variant: "process",
    custom: "aheyaLaunchLoop",
    intent: "X, website/app, direct replies를 launch 성과가 아니라 language/content test surface로 분리한다.",
    claim: "X는 public language/content signal check, website/app은 product explanation과 donation/feedback action path",
    include: ["Pre-launch", "Launch", "Post-launch", "Review", "Iteration"],
    slots: [
      "Hook: problem angle",
      "Visual: asset test",
      "CTA: page entry / donation intent",
      "Review: response cue",
    ],
    process: ["Problem hook", "Visual test", "Page / response CTA", "Response review", "Message iteration", "Direction adjustment"],
  },
  {
    no: 23,
    section: "AHEYA",
    title: "Entry Flow & Landing",
    label: "Activation",
    accent: "cyan",
    variant: "evidence",
    custom: "aheyaLandingCallout",
    intent: "성과 funnel이 아니라 content discovery에서 소액 후원과 상세 피드백까지의 user entry flow를 보여준다.",
    claim: "original X post -> public idea page -> small crypto donation -> detailed feedback -> Share on X -> saved feedback record",
    include: ["Original X post", "Landing", "Donation", "Feedback", "Share on X"],
    slots: [
      "Discovery: X/content에서 문제 훅을 먼저 접함",
      "Landing: hero -> problem -> loop -> saved feedback record -> CTA",
      "Action: donation intent와 detailed feedback을 별도 event 후보로 분리",
      "Boundary: entry-flow design이지 conversion funnel result가 아님",
    ],
    media: { src: "/aheya/page-assets/screens/aheya-aheya-mainpage.webp", alt: "AHEYA homepage screenshot", label: "Landing surface" },
    links: [
      {
        label: "AHEYA site",
        href: "https://aheyabaraya.xyz",
        description: "public product surface",
      },
    ],
  },
  {
    no: 24,
    section: "AHEYA",
    title: "Content Strategy",
    label: "Content Strategy",
    accent: "aqua",
    variant: "evidence",
    custom: "aheyaContentAssetGrid",
    intent: "wallet/onchain mechanics보다 useful AI service idea와 visual hook을 먼저 보여주는 전략을 정리한다.",
    claim: "콘텐츠 자산은 제품 성과 근거가 아니라 복잡한 제품을 발견하게 만드는 visual discovery hook으로 사용",
    include: ["Visual hook", "Repeatable mood", "Public entry", "Boundary"],
    slots: [
      "Purpose: abstract product를 더 쉽게 발견하게 만드는 visual hook",
      "Entry: visual interest에서 public idea page로 이동시키는 첫 touchpoint",
      "Memory: 반복 가능한 mood/character asset으로 기억 가능성 확보",
      "Boundary: visual assets are discovery hooks, not traction proof",
    ],
    gallery: [
      {
        src: "/aheya/worldbuilding/zodiac/aheya-tiger.webp",
        alt: "AHEYA zodiac tiger visual asset",
        label: "Visual hook",
        caption: "Will / resolve motif",
      },
      {
        src: "/aheya/worldbuilding/zodiac/aheya-cow.webp",
        alt: "AHEYA zodiac cow visual asset",
        label: "Repeatable mood",
        caption: "repeatable visual system",
      },
      {
        src: "/aheya/worldbuilding/greek/aheya-athena-img.webp",
        alt: "AHEYA Athena visual asset",
        label: "Signal motif",
        caption: "Wisdom / response motif",
      },
      {
        src: "/aheya/worldbuilding/aheyacharacter/aheya-aheyabaraya-aurora.webp",
        alt: "AHEYA Aurora character visual asset",
        label: "Brand memory",
        caption: "brand-memory asset",
      },
    ],
  },
  {
    no: 25,
    section: "AHEYA",
    title: "X Content Execution",
    label: "Execution",
    accent: "amber",
    variant: "evidence",
    custom: "aheyaXPostGrid",
    intent: "X post를 performance가 아니라 public copy와 product entry iteration ledger로 보여준다.",
    claim: "X posting은 product entry 변경 흐름과 함께 보여준다: original post, small donation, detailed feedback, Share on X",
    include: ["First response", "Response language", "Start from zero"],
    slots: [
      "Phase 1: link/testnet CTA -> product mention",
      "Phase 2: first response / detailed feedback problem -> builder outcome",
      "Phase 3: small crypto donation + Good/Improve feedback + Share on X -> clearer product entry",
      "Product update: technical verification details moved to technical archive",
    ],
    gallery: [
      {
        alt: "AHEYA public X post screenshot from 2026-03-17",
        label: "Strongest public post",
        href: "https://x.com/minnns_aheya/status/2033738008516825288",
        embedUrl: "https://x.com/minnns_aheya/status/2033738008516825288",
        embedType: "x",
        caption: "1,987 impressions / qualitative signal",
      },
      {
        alt: "AHEYA public X post screenshot from 2026-03-27",
        label: "Cleaner response copy",
        href: "https://x.com/minnns_aheya/status/2037465808524460467",
        embedUrl: "https://x.com/minnns_aheya/status/2037465808524460467",
        embedType: "x",
        caption: "donation / feedback language",
      },
      {
        alt: "AHEYA public X post screenshot from 2026-04-10",
        label: "Builder start copy",
        href: "https://x.com/minnns_aheya/status/2042684370486727146",
        embedUrl: "https://x.com/minnns_aheya/status/2042684370486727146",
        embedType: "x",
        caption: "from-zero builder framing",
      },
    ],
  },
  {
    no: 26,
    section: "AHEYA",
    title: "Internal-to-Public Messaging",
    label: "Copy Translation",
    accent: "cyan",
    variant: "matrix",
    custom: "aheyaMessagingEvolution",
    intent: "초기 crypto trading information sharing 기획에서 AI builder 중심 public copy로 좁혀진 흐름을 분리한다.",
    claim: "Public copy shifted from mechanism-first language to user action-first language",
    include: ["Supply-side shift", "Public X copy", "Mechanism", "Technical boundary"],
    slots: ["crypto traders -> AI builders", "reward/quest/funding -> small donation and feedback path", "Share on X is user-led", "technical verification details -> appendix"],
    table: {
      headers: ["Layer", "Before", "After"],
      rows: [
        ["Supply side", "crypto trading information sharing with crypto traders as supply-side", "AI builders with demo/service/tool/agent ideas"],
        ["Internal planning", "reward / quest / funding / token mechanics", "small crypto donation + detailed feedback + saved record"],
        ["Public X copy", "link CTA, testnet, product mention", "first response, public idea page, small donation"],
        ["Mechanism", "technical structure-first explanation", "user action first: open idea, donate, leave feedback, optional Share on X"],
        ["Decision", "complex technical depth in main story", "appendix boundary"],
      ],
    },
  },
  {
    no: 27,
    section: "AHEYA",
    title: "Qualitative Message Check",
    label: "Message Fit",
    accent: "violet",
    variant: "evidence",
    custom: "aheyaOutreachGrid",
    intent: "public reply 기반 message clarity와 segment fit 확인을 private evidence와 분리한다.",
    claim: "Public replies were used only to check message clarity and segment fit, not external deal evidence",
    include: ["Exploratory", "Relevant segment", "High-fit builder", "Privacy boundary"],
    slots: [
      "Exploratory message: vibe coding / AI agents 대상 donation/feedback path 제안",
      "Relevant segment message: AI-native creators working on tools, agents, games",
      "High-fit builder message: founder-first response system for live demos",
      "Boundary: private DM body, handle, account ID excluded",
    ],
    gallery: [
      {
        alt: "AHEYA public X embed from 2026-04-01",
        label: "Live demo CTA",
        href: "https://x.com/minnns_aheya/status/2039382534354870308",
        embedUrl: "https://x.com/minnns_aheya/status/2039382534354870308",
        embedType: "x",
        caption: "donation and feedback flow CTA",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-03-19.png",
        alt: "AHEYA public reply screenshot from 2026-03-19",
        label: "Relevant segment reply",
        href: "https://x.com/minnns_aheya/status/2034680247053164585",
        caption: "AI-native creator segment",
      },
      {
        src: "/aheya/ppt/x-cards/aheya-reply-2026-04-02.png",
        alt: "AHEYA public reply screenshot from 2026-04-02",
        label: "High-fit builder reply",
        href: "https://x.com/minnns_aheya/status/2039543700045656099",
        caption: "founder-first response",
      },
    ],
    links: [
      {
        label: "X account",
        href: "https://x.com/minnns_aheya",
        description: "public content surface",
      },
    ],
  },
  {
    no: 28,
    section: "AHEYA",
    title: "Pre-Decision Signal Review",
    label: "Signal Read",
    accent: "aqua",
    variant: "matrix",
    custom: "aheyaSignalSplit",
    intent: "앞단 X, product surface, KPI/SQL 설계를 결론 직전 판단 재료로 정리한다.",
    claim: "X 반응과 KPI 설계는 다음 판단을 위한 signal review로만 사용한다.",
    include: ["X/content evidence", "Product surface", "KPI/SQL design", "Decision boundary"],
    slots: ["Public X post/reply evidence", "Landing and donation/feedback surface", "Event/source mapping", "No outcome claim"],
    table: {
      headers: ["Source", "Signal read", "Decision use"],
      rows: [
        ["X / content", "public post, reply, representative post metric은 어떤 언어와 visual hook이 attention을 받는지 보는 표면", "content angle과 outreach wording을 조정하는 재료"],
        ["Product surface", "landing, project page, 소액 후원, detailed feedback path는 첫 action이 가능한지 확인하는 구현 표면", "다음 MVP에서 남길 행동과 줄일 설명을 판단"],
        ["KPI / SQL design", "site_visit, project_open, donation_intent, feedback_submit, share_on_x, feedback_record_created를 event/source 후보로 분리", "성과 숫자가 아니라 이후 read-only snapshot의 기준선"],
        ["Boundary", "current deck에서는 traction number나 metric lift를 결론으로 쓰지 않음", "29번은 방향 판단과 다음 측정 구조로만 연결"],
      ],
    },
  },
  {
    no: 29,
    section: "AHEYA",
    title: "Decision & Learning",
    label: "Decision",
    accent: "amber",
    variant: "matrix",
    custom: "aheyaDecisionClose",
    intent: "AHEYA의 결론을 검증 성공이 아니라 방향 판단으로 정리한다.",
    claim: "AHEYA는 기술 구조보다 public idea, 암호화폐 소액 후원, 상세 피드백, Share on X, saved record를 먼저 보여주는 방향으로 정리했다",
    include: ["Continue", "Lower", "Separate", "Next"],
    slots: ["Product story became simpler", "Small crypto donation remained as a visible product action", "Share on X stayed user-led", "KPI/SQL stayed as measurement design"],
    table: {
      headers: ["What this proves", "Portfolio read", "Evidence boundary"],
      rows: [
        ["PM", "Narrowed a broad reward/quest/funding idea into a visible idea/donation/feedback/share flow.", "scope and decision trace, not traction proof"],
        ["GTM", "Moved from technical-structure-first language to builder-outcome messaging.", "message clarity, not demand proof"],
        ["Content", "Used visual and X content as discovery hooks.", "attention cue, not traction proof"],
        ["Data", "Designed KPI/event/SQL structure without overstating performance.", "measurement design, not metric proof"],
      ],
    },
    media: { src: "/aheya/ppt/aheya-core-rail-flow.svg", alt: "AHEYA donation and feedback flow recap", label: "Decision recap" },
  },
] satisfies Slide[];
