import type { Slide } from "../types";

export const commonSlides = [
  {
    no: 1,
    section: "Common",
    title: "Cover / Positioning",
    label: "Portfolio Positioning",
    accent: "violet",
    variant: "cover",
    intent: "첫 화면에서 포트폴리오의 정체성을 바로 보여준다.",
    claim:
      "초기 아이디어를 제품 구조, 시장 메시지, 콘텐츠 실험, 시장 신호로 전환합니다.",
    include: [
      "Product & GTM Portfolio",
      "AI-driven Content Experiments",
      "Early-stage ideas to market signals",
      "AHEYA / ADSB / AB-Luna / SFTI",
    ],
    slots: ["Master Title", "One-line Positioning", "Main / Support Case Tiles", "Contact / Target Role"],
    note: "Master expression: I turn early-stage ideas into product, message, content, and market signals.",
    media: {
      src: "/aheya/aheya-home-hero.webp",
      alt: "AHEYA visual placeholder",
      label: "AHEYA hero asset",
    },
  },
  {
    no: 2,
    section: "Common",
    title: "Profile Snapshot",
    label: "Fast Read",
    accent: "cyan",
    variant: "matrix",
    intent: "지원 직무와 핵심 역량을 빠르게 보여주는 요약 페이지.",
    claim: "지원 직무, 반복적으로 맡는 일, 증거가 되는 케이스를 한 장에서 스캔하게 만든다.",
    include: ["Target Roles", "Work I Do", "Tools", "Proof Cases"],
    slots: ["Fast-read Summary", "Tool Stack Rail", "Representative Proof Chips"],
    table: {
      headers: ["Category", "Summary"],
      rows: [
        ["Target Roles", "Product Planning, GTM, Marketing, Content Strategy"],
        ["Work I Do", "Define problems, structure product, shape messages, produce content, review signals"],
        ["Strengths", "Problem Definition, Messaging, AI-assisted Content Execution, Decision Logs"],
        ["Tools", "GPT, Claude, Grok, Codex, Supabase, React/Next.js"],
        ["Main Cases", "AHEYA, ADSB, AB-Luna, SFTI-CMU"],
      ],
    },
  },
  {
    no: 3,
    section: "Common",
    title: "About",
    label: "Identity",
    accent: "amber",
    variant: "split",
    intent: "단순 자기소개가 아니라 포트폴리오 전체를 해석하는 기준을 제시한다.",
    claim: "모호한 초기 문제를 제품, 메시지, 콘텐츠, 판단 기록으로 바꾸는 AI-native 기획자.",
    include: ["One-line Identity", "What I Work On", "How I Prove It"],
    slots: ["Identity Copy", "Work Principle", "Repeated Problem", "Evidence Preview"],
    note:
      "저는 문제, 사용자 진입점, 시장 메시지, 첫 반응이 불분명한 초기 프로젝트를 구조화된 실험물로 바꾸는 일을 합니다.",
  },
  {
    no: 4,
    section: "Common",
    title: "Core Strengths",
    label: "Capability Map",
    accent: "aqua",
    variant: "matrix",
    intent: "PM / GTM / Marketing / Content 관점의 핵심 역량을 한 장에서 보여준다.",
    claim: "제품 구조화, 시장-facing 메시지, 콘텐츠 실행, 신호 기반 판단을 분리해 보여준다.",
    include: ["Product", "GTM", "Marketing", "Content", "Decision"],
    slots: ["Five Capability Cards", "Evidence Tag Per Area", "Role-fit Caption"],
    table: {
      headers: ["Area", "Strength"],
      rows: [
        ["Product", "문제 정의, MVP 범위, 유저 플로우, 위험도 높은 기능 제외"],
        ["GTM", "타깃, 포지셔닝, 메시지 프레임워크, 채널 가설"],
        ["Marketing", "콘텐츠 훅, SNS 실험, first-touch 이해도 개선"],
        ["Content", "이미지/영상 기획, 숏폼 구조, AI-assisted workflow"],
        ["Decision", "강한/약한 신호를 구분하고 계속 / 축소 / 전환 판단"],
      ],
    },
  },
  {
    no: 5,
    section: "Common",
    title: "Working Process",
    label: "Operating Model",
    accent: "violet",
    variant: "process",
    intent: "내가 일하는 방식을 구조화해서 보여준다.",
    claim: "Research에서 시작해 구조화, 제작, 공개/테스트, 학습, 판단까지 한 흐름으로 일한다.",
    include: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    slots: ["Process Flow", "One-line Rule Per Step", "Decision Output"],
    process: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    note: "각 케이스는 무엇을 만들었는지보다 어떤 신호를 보고 어떤 결정을 내렸는지까지 읽히게 구성한다.",
  },
  {
    no: 6,
    section: "Common",
    title: "Portfolio Reading Guide",
    label: "How to Read",
    accent: "amber",
    variant: "split",
    intent: "채용자가 이 포트폴리오를 어떤 관점으로 읽어야 하는지 안내한다.",
    claim: "AHEYA는 product/GTM/content 사고, ADSB는 AI-assisted creative execution, AB-Luna/SFTI는 보강 증거로 읽는다.",
    include: [
      "AHEYA: Product / GTM / Content Thinking",
      "ADSB: AI-assisted Creative Execution",
      "AB-Luna: AI Workflow / MVP Support",
      "SFTI: Research Writing Support",
      "Reviewer Lens: role-fit evidence by case",
    ],
    slots: ["Case Reading Cards", "Main / Support Separation", "Evidence Lens", "Reviewer Note"],
    note: "각 케이스는 역할, 산출물, 판단 기준이 다르게 읽히도록 분리한다.",
  },
  {
    no: 7,
    section: "Common",
    title: "Case Map",
    label: "Case Separation",
    accent: "cyan",
    variant: "matrix",
    intent: "AHEYA, ADSB, AB-Luna, SFTI의 역할을 명확히 분리한다.",
    claim: "두 개의 main case와 두 개의 support case가 서로 다른 역량 증거를 담당하게 만든다.",
    include: ["Case", "Role in Portfolio", "What It Proves", "Proof Artifact"],
    slots: ["Case Comparison Table", "Main / Supporting Badge", "Evidence Summary"],
    table: {
      headers: ["Case", "Role in Portfolio", "What It Proves"],
      rows: [
        ["AHEYA", "Flagship Main", "Problem definition, MVP scope, messaging, content experiment, signal-based decision"],
        ["ADSB", "Second Main", "Brand mood interpretation, prompt structure, image/video direction, storyboard flow"],
        ["AB-Luna", "Support", "AI workflow, handoff MVP, user input structure, KPI readiness"],
        ["SFTI-CMU", "Support", "Research translation, English abstract, poster narrative, external-ready writing"],
      ],
    },
  },
  {
    no: 8,
    section: "Common",
    title: "Role Fit Summary",
    label: "Hiring Signal",
    accent: "aqua",
    variant: "matrix",
    intent: "지원 직무별로 이 포트폴리오가 무엇을 증명하는지 요약한다.",
    claim: "PM, GTM, Marketing, Content 역할에서 어떤 증거를 먼저 보면 되는지 한 장으로 정리한다.",
    include: ["PM Evidence", "GTM Evidence", "Marketing Evidence", "Content Evidence", "AI Workflow Evidence"],
    slots: ["Role Evidence Matrix", "Main Evidence Column", "Supporting Evidence Column"],
    table: {
      headers: ["Role", "Main Evidence", "Supporting Evidence"],
      rows: [
        ["PM", "AHEYA: 문제 정의, MVP scope, 유저 플로우, 판단 기준", "AB-Luna: problem definition, handoff MVP, KPI readiness"],
        ["GTM", "AHEYA: 타깃, 포지셔닝, 메시지, 채널 가설", "AB-Luna: market definition / ADSB: campaign context"],
        ["Marketing", "AHEYA: 콘텐츠 훅, SNS 실험, early signal review", "ADSB: 브랜드 무드와 숏폼 콘텐츠 방향 해석"],
        ["Content", "ADSB: AI-assisted visual, prompt, storyboard workflow", "AHEYA: symbolic visual entry / SFTI: English narrative"],
        ["AI Workflow", "ADSB: prompt iteration and asset selection criteria", "AB-Luna: AI handoff workflow and form-based input"],
      ],
    },
    note: "각 역할이 확인할 수 있는 산출물, 화면, 콘텐츠, 판단 과정을 먼저 연결한다.",
  },
] satisfies Slide[];
