import type { Slide } from "../types";

export const commonSlides = [
  {
    no: 1,
    section: "Common",
    title: "Cover / Positioning",
    label: "Portfolio Positioning",
    accent: "violet",
    variant: "cover",
    intent: "첫 화면에서 Product / GTM / AI-assisted Execution 중심 포트폴리오임을 바로 보여준다.",
    claim: "초기 아이디어를 제품 구조, GTM 메시지, AI-assisted execution loop로 전환합니다.",
    include: [
      "AHEYA: Product / GTM Planning + Signal Review",
      "ADSB: AI-assisted Content Execution",
      "AB-Luna / SFTI-CMU: Supporting Evidence",
      "No traction claim without evidence",
    ],
    slots: ["Master Title", "One-line Positioning", "Main / Support Case Tiles", "Contact / Target Role"],
    note:
      "Master expression: Product/GTM planning first; AI-assisted execution and content workflow support the product/GTM loop.",
    media: {
      src: "/aheya/aheya-home-hero.webp",
      alt: "AHEYA visual placeholder",
      label: "AHEYA hero asset",
    },
  },
  {
    no: 2,
    section: "Common",
    title: "Profile Snapshot",
    label: "Fast Read",
    accent: "cyan",
    variant: "matrix",
    intent: "지원 직무 렌즈와 핵심 역량을 빠르게 보여주는 요약 페이지.",
    claim: "Product/GTM/AI-assisted execution을 고정 직무명이 아니라 공통 역량 축으로 읽게 만든다.",
    include: ["Target Lens", "Work I Do", "Tools", "Evidence Cases"],
    slots: ["Fast-read Summary", "Tool Stack Rail", "Representative Evidence Chips"],
    table: {
      headers: ["Category", "Summary"],
      rows: [
        ["Target Lens", "Product/GTM-oriented roles where planning, messaging, execution, and signal review overlap"],
        ["Work I Do", "Define problems, structure product/GTM systems, shape messages, execute with AI workflows, review signals"],
        ["Main Evidence", "AHEYA: product/GTM planning + signal review / ADSB: AI-assisted content execution"],
        ["Tools", "GPT, Claude, Grok, Codex, Supabase, React/Next.js"],
        ["Support Evidence", "AB-Luna: AI workflow support / SFTI-CMU: research communication support"],
      ],
    },
    note:
      "Submission customization: replace only the Target Lens row per application, e.g. Product Strategy / Product Marketing, GTM Strategy / Marketing Strategy, AI Content Marketing / Creative Planning, or AI-assisted Workflow / Product Operations.",
  },
  {
    no: 3,
    section: "Common",
    title: "About",
    label: "Identity",
    accent: "amber",
    variant: "split",
    intent: "단순 자기소개가 아니라 포트폴리오 전체를 해석하는 기준을 제시한다.",
    claim: "모호한 초기 문제를 제품 구조, GTM 메시지, AI-assisted execution loop, 판단 근거로 바꾸는 AI-native 기획자.",
    include: ["One-line Identity", "What I Work On", "How I Show It"],
    slots: ["Identity Copy", "Work Principle", "Repeated Problem", "Evidence Preview"],
    note:
      "저는 문제, 사용자 진입점, 시장 메시지, 첫 반응이 불분명한 초기 프로젝트를 제품/GTM 구조와 실행 가능한 콘텐츠/신호 단위로 바꾸는 일을 합니다.",
  },
  {
    no: 4,
    section: "Common",
    title: "Core Strengths",
    label: "Capability Map",
    accent: "aqua",
    variant: "matrix",
    intent: "Product / GTM / AI-assisted Execution 관점의 핵심 역량을 한 장에서 보여준다.",
    claim: "제품/GTM 구조화를 중심으로, 메시지·AI workflow·콘텐츠 실행·신호 판단을 역할별 증거로 분리해 보여준다.",
    include: ["Product", "GTM", "AI-assisted Execution", "Marketing / GTM Content", "Decision"],
    slots: ["Five Capability Cards", "Evidence Tag Per Area", "Role-fit Caption"],
    table: {
      headers: ["Area", "Strength"],
      rows: [
        ["Product", "문제 정의, MVP 범위, 유저 플로우, 위험도 높은 기능 제외"],
        ["GTM", "타깃, 포지셔닝, 메시지 프레임워크, 채널 가설"],
        ["AI-assisted Execution", "AI workflow를 사용한 문서화, 제작, iteration, handoff"],
        ["Marketing / GTM Content", "메시지-콘텐츠 연결, visual hook, first-touch 이해도 개선"],
        ["Decision", "강한/약한 신호를 구분하고 계속 / 축소 / 전환 판단"],
      ],
    },
  },
  {
    no: 5,
    section: "Common",
    title: "Working Process",
    label: "Operating Model",
    accent: "violet",
    variant: "process",
    intent: "내가 일하는 방식을 구조화해서 보여준다.",
    claim: "Research에서 시작해 구조화, 제작, 공개/테스트, 학습, 판단까지 한 흐름으로 일한다.",
    include: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    slots: ["Process Flow", "One-line Rule Per Step", "Decision Output"],
    process: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    note: "각 케이스는 무엇을 만들었는지보다 어떤 신호를 보고 어떤 결정을 내렸는지까지 읽히게 구성한다.",
  },
  {
    no: 6,
    section: "Common",
    title: "Portfolio Reading Guide",
    label: "How to Read",
    accent: "amber",
    variant: "split",
    intent: "채용자가 이 포트폴리오를 어떤 관점으로 읽어야 하는지 안내한다.",
    claim: "AHEYA를 flagship case로, ADSB를 second main execution case로, AB-Luna와 SFTI-CMU를 support evidence로 읽는다.",
    include: [
      "AHEYA: Product / GTM Planning + Signal Review",
      "ADSB: AI-assisted Content Execution / Short-form Direction",
      "AB-Luna: AI Workflow / MVP Support",
      "SFTI: Research Communication Support",
      "Reviewer Lens: role-fit evidence by case",
    ],
    slots: ["Case Reading Cards", "Main / Support Separation", "Evidence Lens", "Reviewer Note"],
    note: "각 케이스는 역할, 산출물, 판단 기준이 다르게 읽히도록 분리한다.",
  },
  {
    no: 7,
    section: "Common",
    title: "Case Map",
    label: "Case Separation",
    accent: "cyan",
    variant: "matrix",
    intent: "AHEYA, ADSB, AB-Luna, SFTI의 역할을 명확히 분리한다.",
    claim: "두 개의 main case와 두 개의 support case가 서로 다른 역량 증거를 담당한다.",
    include: ["Case", "Role in Portfolio", "What It Shows", "Evidence Artifact"],
    slots: ["Case Comparison Table", "Main / Supporting Badge", "Evidence Summary"],
    table: {
      headers: ["Case", "Role in Portfolio", "What It Shows"],
      rows: [
        ["AHEYA", "Flagship Case", "Product/GTM planning: problem definition, MVP scope, messaging, signal review"],
        ["ADSB", "Second Main Case", "AI-assisted execution: brand reading, prompt/motion direction, final Reel output"],
        ["AB-Luna", "Supporting Evidence", "AI workflow support: handoff MVP, user input structure, KPI readiness"],
        ["SFTI-CMU", "Supporting Evidence", "Research communication support: English abstract, poster narrative, external reader-ready writing"],
      ],
    },
  },
  {
    no: 8,
    section: "Common",
    title: "Role Fit Summary",
    label: "Hiring Signal",
    accent: "aqua",
    variant: "matrix",
    intent: "지원 직무별로 이 포트폴리오가 무엇을 보여주는지 요약한다.",
    claim: "Product Planning, GTM Strategy, AI-assisted Execution 관점에서 어떤 케이스를 먼저 보면 되는지 정리한다.",
    include: ["Product Evidence", "GTM Evidence", "AI-assisted Execution Evidence", "Marketing / GTM Content Evidence", "Working Method"],
    slots: ["Role Evidence Matrix", "Main Evidence Column", "Supporting Evidence Column"],
    table: {
      headers: ["Role", "Main Evidence", "Supporting Evidence"],
      rows: [
        ["Product Planning", "AHEYA: 문제 정의, MVP scope, 유저 플로우, 판단 기준", "AB-Luna: problem definition, handoff MVP, KPI readiness"],
        ["GTM Strategy", "AHEYA: 타깃, 포지셔닝, 메시지, 채널 가설", "ADSB: content context / AB-Luna: market definition"],
        ["AI-assisted Execution", "AHEYA: planning, documentation, signal review workflow", "ADSB: prompt, image-to-video iteration, final Reel output"],
        ["Marketing / GTM Content", "AHEYA: 콘텐츠 훅, SNS 실험, early signal review", "ADSB: brand mood and short-form direction"],
        ["Working Method", "Research -> Structure -> Build/Produce -> Publish/Test -> Learn/Decide", "AB-Luna/SFTI: support evidence"],
      ],
    },
    note: "각 역할이 확인할 수 있는 산출물, 화면, 콘텐츠, 판단 과정을 먼저 연결한다.",
  },
] satisfies Slide[];
