import type { Slide } from "../types";

export const commonSlides = [
  {
    no: 1,
    section: "Common",
    title: "Product/GTM Planner",
    label: "AI-assisted Execution & Signal Review",
    accent: "violet",
    variant: "cover",
    intent: "첫 화면에서 Product/GTM Planner — AI-assisted Execution & Signal Review 중심 포트폴리오임을 바로 보여준다.",
    claim: "초기 아이디어를 제품 구조, GTM 메시지, AI-assisted 실행 루프, 다음 판단 단위로 좁힙니다.",
    include: [
      "AHEYA: First-signal Product/GTM Planning",
      "ADSB: AI Short-form Creative Direction",
      "AB-Luna / SFTI-CMU: Supporting Evidence",
      "No performance claim without public evidence",
    ],
    slots: ["Master Title", "One-line Positioning", "Main / Support Case Tiles", "Contact / Target Role"],
    note:
      "Master expression: Product/GTM planning first; AI-assisted execution and content workflow support the product/GTM loop.",
    media: {
      src: "/aheya/aheya-home-hero.webp",
      alt: "AHEYA visual placeholder",
      label: "AHEYA hero asset",
    },
  },
  {
    no: 2,
    section: "Common",
    title: "Profile Snapshot",
    label: "Fast Read",
    accent: "cyan",
    variant: "matrix",
    intent: "지원 직무 렌즈와 핵심 역량을 빠르게 보여주는 요약 페이지.",
    claim: "Product/GTM planner를 중심으로, AI-assisted 실행과 signal review를 보조 역량으로 읽게 만든다.",
    include: ["Target Lens", "Work I Do", "Tools", "Evidence Cases"],
    slots: ["Fast-read Summary", "Tool Stack Rail", "Representative Evidence Chips"],
    table: {
      headers: ["Category", "Summary"],
      rows: [
        ["Target Lens", "Product/GTM planning roles where problem framing, message structure, execution loop, and signal review overlap"],
        ["Work I Do", "Narrow ambiguous ideas into product structure, GTM message, AI-assisted 실행 루프, and next decision units"],
        ["Main Evidence", "AHEYA: first-signal product/GTM planning / ADSB: AI short-form creative direction"],
        ["Tools", "GPT, Claude, Grok, Codex, Supabase, React/Next.js"],
        ["Support Evidence", "AB-Luna: workflow support / SFTI-CMU: research communication support"],
      ],
    },
    note:
      "Submission customization: replace only the Target Lens row per application, e.g. Product Strategy / Product Marketing, GTM Strategy / Marketing Strategy, AI Content Marketing / Creative Planning, or AI-assisted Workflow / Product Operations.",
  },
  {
    no: 3,
    section: "Common",
    title: "About",
    label: "Identity",
    accent: "amber",
    variant: "split",
    intent: "단순 자기소개가 아니라 포트폴리오 전체를 해석하는 기준을 제시한다.",
    claim: "모호한 초기 문제를 제품 구조, GTM 메시지, AI-assisted 실행 루프, 판단 근거로 좁히는 Product/GTM planner입니다.",
    include: ["One-line Identity", "What I Work On", "How I Show It"],
    slots: ["Identity Copy", "Work Principle", "Repeated Problem", "Evidence Preview"],
    note:
      "저는 문제, 사용자 진입점, 시장 메시지, 첫 반응이 불분명한 초기 프로젝트를 제품/GTM 구조와 실행 가능한 콘텐츠/신호 단위로 바꾸는 일을 합니다.",
  },
  {
    no: 4,
    section: "Common",
    title: "Core Strengths",
    label: "Capability Map",
    accent: "aqua",
    variant: "matrix",
    intent: "Product/GTM Planning, AI-assisted Execution, Signal Review 관점의 핵심 역량을 한 장에서 보여준다.",
    claim: "제품/GTM 구조화를 중심에 두고, AI-assisted 실행과 signal review를 다음 판단 단위로 연결한다.",
    include: ["Product/GTM Planning", "AI-assisted Execution", "Signal Review & Decision Read Model"],
    slots: ["Three Capability Cards", "Evidence Tag Per Area", "Role-fit Caption"],
    table: {
      headers: ["Area", "Strength"],
      rows: [
        ["Product/GTM Planning", "문제 정의, MVP 범위, 타깃, 메시지 프레임워크, 위험도 높은 기능 제외"],
        ["AI-assisted Execution", "AI workflow를 사용한 문서화, 제작, iteration, handoff"],
        ["Signal Review & Decision Read Model", "public copy, product action, event unit을 분리해 다음 판단 기준으로 읽기"],
      ],
    },
  },
  {
    no: 5,
    section: "Common",
    title: "Working Process",
    label: "Operating Model",
    accent: "violet",
    variant: "process",
    intent: "내가 일하는 방식을 구조화해서 보여준다.",
    claim: "Research에서 시작해 구조화, 제작, 공개/테스트, signal review, 다음 판단까지 한 흐름으로 좁힌다.",
    include: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    slots: ["Process Flow", "One-line Rule Per Step", "Decision Output"],
    process: ["Research", "Structure", "Build / Produce", "Publish / Test", "Learn", "Decide"],
    note: "각 케이스는 무엇을 만들었는지보다 어떤 신호를 보고 어떤 결정을 내렸는지까지 읽히게 구성한다.",
  },
  {
    no: 6,
    section: "Common",
    title: "Portfolio Reading Guide",
    label: "How to Read",
    accent: "amber",
    variant: "split",
    intent: "채용자가 이 포트폴리오를 어떤 관점으로 읽어야 하는지 안내한다.",
    claim: "AHEYA는 flagship product/GTM planning case, ADSB는 second main creative direction case, AB-Luna와 SFTI-CMU는 support evidence로 읽는다.",
    include: [
      "AHEYA: AI service idea를 행동 경로, 메시지, 측정 단위로 좁힌 사례",
      "ADSB: shared brand reading을 hook, motif rule, prompt/motion direction으로 수렴시킨 사례",
      "AB-Luna: AI output 이후 handoff 문제를 product layer로 정의한 support evidence",
      "SFTI: 감각적 AI content idea를 external reader-ready research structure로 재배치한 support evidence",
      "Reviewer Lens: role-fit evidence by case",
    ],
    slots: ["Case Reading Cards", "Main / Support Separation", "Evidence Lens", "Reviewer Note"],
    note: "각 케이스는 역할, 산출물, 판단 기준이 다르게 읽히도록 분리한다.",
  },
  {
    no: 7,
    section: "Common",
    title: "Case Map",
    label: "Case Separation",
    accent: "cyan",
    variant: "matrix",
    intent: "AHEYA, ADSB, AB-Luna, SFTI의 역할을 명확히 분리한다.",
    claim: "두 개의 main case와 두 개의 support case가 서로 다른 역량 증거를 담당한다.",
    include: ["Case", "Role in Portfolio", "What It Shows", "Evidence Artifact"],
    slots: ["Case Comparison Table", "Main / Supporting Badge", "Evidence Summary"],
    table: {
      headers: ["Case", "Role in Portfolio", "What It Shows"],
      rows: [
        ["AHEYA", "Flagship Product/GTM Planning Case", "AI service idea를 행동 경로, 메시지, 측정 단위로 좁힌 first-signal planning"],
        ["ADSB", "Second Main Creative Direction Case", "Shared brand reading을 hook, motif rule, prompt/motion direction으로 수렴"],
        ["AB-Luna", "Workflow Support Evidence", "AI output 이후 handoff 문제를 product layer로 정의"],
        ["SFTI-CMU", "Research Communication Support Evidence", "감각적 AI content idea를 external reader-ready research structure로 재배치"],
      ],
    },
  },
  {
    no: 8,
    section: "Common",
    title: "Role Fit Summary",
    label: "Hiring Signal",
    accent: "aqua",
    variant: "matrix",
    intent: "지원 직무별로 이 포트폴리오가 무엇을 보여주는지 요약한다.",
    claim: "Primary fit은 Product/GTM Planning이며, AI-assisted execution과 signal review는 이를 증명하는 실행 방식이다.",
    include: ["Primary Fit", "Main Evidence", "Execution Evidence", "Support Evidence", "Working Method"],
    slots: ["Role Evidence Matrix", "Main Evidence Column", "Supporting Evidence Column"],
    table: {
      headers: ["Role", "Main Evidence", "Supporting Evidence"],
      rows: [
        ["Primary Fit", "AHEYA: 문제 정의, MVP scope, message framing, decision unit", "Product/GTM planning 중심"],
        ["GTM Strategy", "AHEYA: 타깃, 포지셔닝, public copy, channel role", "ADSB: brand mood and short-form direction"],
        ["AI-assisted Execution", "AHEYA: planning/documentation loop / ADSB: prompt, storyboard, image-to-video iteration", "AI는 방식, claim은 판단 구조"],
        ["Signal Review", "AHEYA: public copy, product action, event unit을 분리한 measurement read model", "AB-Luna: workflow readiness"],
        ["Support Evidence", "AB-Luna: handoff layer / SFTI-CMU: research communication structure", "Main case 보강 증거"],
      ],
    },
    note: "각 역할이 확인할 수 있는 산출물, 화면, 콘텐츠, 판단 과정을 먼저 연결한다.",
  },
] satisfies Slide[];
