import "server-only";

import { readFile, stat } from "node:fs/promises";

export type EvidenceArea = "Pulso" | "Ink" | "Workbench" | "AHEYA";

export type InternalEvidenceArtifact = {
  id: string;
  area: EvidenceArea;
  stage: string;
  title: string;
  fileName: string;
  displayPath: string;
  sourcePath: string;
  format: string;
  supports: string;
  boundary: string;
};

const PULSO_ROOT = "/Users/yuminseog/aheyabaraya_hq_root/hq-control/creative/IDOL/runs/2026-06-11/0611_WORLD_CUP_PULSO";
const INK_CATALOG_ROOT = "/Users/yuminseog/aheyabaraya_hq_root/hq-control/creative/IDOL/catalog/albums/ink/ink";
const WORKBENCH_ROOT = "/Users/yuminseog/aheyabaraya_hq_root/hq-control/creative/IDOL/development/front-planning-workbench";
const AHEYA_ROOT = "/Users/yuminseog/aheyabaraya_hq_root/aheyabaraya";

export const internalEvidenceArtifacts: InternalEvidenceArtifact[] = [
  {
    id: "pulso-readiness",
    area: "Pulso",
    stage: "01 / Research handoff",
    title: "Front planning readiness",
    fileName: "front-planning-readiness-v1.yaml",
    displayPath: "PULSO / research/front-planning-readiness-v1.yaml",
    sourcePath: `${PULSO_ROOT}/research/front-planning-readiness-v1.yaml`,
    format: "YAML production record",
    supports: "음원·컷·가사·비주얼 보드·의상 판단을 downstream 단계에 넘기는 기준과 자동화 경계를 확인합니다.",
    boundary: "자동화가 창의 해석이나 기본 선택을 하지 않도록 명시한 실제 planning record입니다.",
  },
  {
    id: "pulso-nucleus",
    area: "Pulso",
    stage: "02 / Creative lock",
    title: "Creative nucleus",
    fileName: "00-creative-nucleus.yaml",
    displayPath: "PULSO / 00-creative-nucleus.yaml",
    sourcePath: `${PULSO_ROOT}/00-creative-nucleus.yaml`,
    format: "YAML creative direction record",
    supports: "메시지, 시각 세계, 장면 흐름, 유지할 요소와 피할 요소를 제작 전 기준으로 잡은 기록입니다.",
    boundary: "생성 프롬프트가 아니라 사람이 세운 메시지와 선택의 기준입니다.",
  },
  {
    id: "pulso-song-lock",
    area: "Pulso",
    stage: "02 / Creative lock",
    title: "Song lock",
    fileName: "00A-song-lock.yaml",
    displayPath: "PULSO / 00A-song-lock.yaml",
    sourcePath: `${PULSO_ROOT}/00A-song-lock.yaml`,
    format: "YAML production lock",
    supports: "선정된 오디오와 작업 기준을 이후 화면·편집 단계가 참조하는 고정점으로 만듭니다.",
    boundary: "곡과 메시지의 최종 해석을 자동으로 결정했다는 근거는 아닙니다.",
  },
  {
    id: "pulso-direction-map",
    area: "Pulso",
    stage: "03 / Direction & coverage",
    title: "Song, choreography, performance MV map",
    fileName: "01-song-choreography-performance-mv-map.yaml",
    displayPath: "PULSO / 01-song-choreography-performance-mv-map.yaml",
    sourcePath: `${PULSO_ROOT}/01-song-choreography-performance-mv-map.yaml`,
    format: "YAML direction map",
    supports: "음원 구간을 퍼포먼스, 카메라, 오브젝트, 컷 흐름으로 옮기는 방향 기록입니다.",
    boundary: "이 파일은 촬영 현장의 연출 기록이 아니라 AI 기반 영상 제작을 위한 방향 맵입니다.",
  },
  {
    id: "pulso-visual-board",
    area: "Pulso",
    stage: "03 / Direction & coverage",
    title: "Track visual board",
    fileName: "01A-track-visual-board.yaml",
    displayPath: "PULSO / 01A-track-visual-board.yaml",
    sourcePath: `${PULSO_ROOT}/01A-track-visual-board.yaml`,
    format: "YAML visual board",
    supports: "세계관, 인물, 의상, 화면 질감의 기준을 장면 생산 전에 맞춥니다.",
    boundary: "한 장의 결과물을 고른 갤러리가 아니라 이후 후보를 걸러낼 시각 기준입니다.",
  },
  {
    id: "pulso-generation-map",
    area: "Pulso",
    stage: "03 / Direction & coverage",
    title: "Generation map",
    fileName: "02-generation-map.yaml",
    displayPath: "PULSO / 02-generation-map.yaml",
    sourcePath: `${PULSO_ROOT}/02-generation-map.yaml`,
    format: "YAML coverage plan",
    supports: "각 화면에서 무엇을 생성하고 어떤 역할로 쓸지 분리한 coverage 계획을 보여줍니다.",
    boundary: "생성량 자체가 품질을 보증하지 않으며, 다음 review gate가 별도로 존재합니다.",
  },
  {
    id: "pulso-storyboard",
    area: "Pulso",
    stage: "04 / Keyframe gate",
    title: "Master storyboard",
    fileName: "02A-master-storyboard.yaml",
    displayPath: "PULSO / 02A-master-storyboard.yaml",
    sourcePath: `${PULSO_ROOT}/02A-master-storyboard.yaml`,
    format: "YAML storyboard record",
    supports: "키프레임 단위의 컷 역할, 연결, 검토 대상이 생성 이전에 구조화된 방식을 보여줍니다.",
    boundary: "완성 영상의 편집본이 아니라 review 이전의 계획·판단 기록입니다.",
  },
  {
    id: "pulso-prompt-packets",
    area: "Pulso",
    stage: "04 / Keyframe gate",
    title: "Prompt packets",
    fileName: "02B-prompt-packets.yaml",
    displayPath: "PULSO / 02B-prompt-packets.yaml",
    sourcePath: `${PULSO_ROOT}/02B-prompt-packets.yaml`,
    format: "YAML execution packet",
    supports: "검토된 화면 계획을 실행 가능한 생성 단위로 변환한 방식을 확인합니다.",
    boundary: "프롬프트가 창의 결정을 새로 만들도록 두지 않고, 앞 단계의 선택을 실행하는 단위입니다.",
  },
  {
    id: "pulso-review",
    area: "Pulso",
    stage: "05 / Review & edit",
    title: "Review record",
    fileName: "03-review.yaml",
    displayPath: "PULSO / 03-review.yaml",
    sourcePath: `${PULSO_ROOT}/03-review.yaml`,
    format: "YAML review record",
    supports: "통과·보류·수정의 근거를 남기고 다음 제작 단위를 바꾸는 검토 방식을 보여줍니다.",
    boundary: "모든 생성 후보가 자동 통과했다는 뜻이 아니라, 명시적 검토를 거친다는 증거입니다.",
  },
  {
    id: "pulso-edit-map",
    area: "Pulso",
    stage: "05 / Review & edit",
    title: "Edit map",
    fileName: "04-edit-map.yaml",
    displayPath: "PULSO / 04-edit-map.yaml",
    sourcePath: `${PULSO_ROOT}/04-edit-map.yaml`,
    format: "YAML edit recipe",
    supports: "선택된 구간과 순서를 편집 가능한 recipe로 정리한 방식을 보여줍니다.",
    boundary: "Premiere나 CapCut을 대체하는 편집 제품이 아니라, 후보 선택과 타이밍 검수를 돕는 제작 기록입니다.",
  },
  {
    id: "pulso-package",
    area: "Pulso",
    stage: "06 / Package & archive",
    title: "Release package",
    fileName: "05-package.yaml",
    displayPath: "PULSO / 05-package.yaml",
    sourcePath: `${PULSO_ROOT}/05-package.yaml`,
    format: "YAML release package",
    supports: "완료된 산출물과 다음 공개·재사용 단위로 넘기는 패키징 기록을 확인합니다.",
    boundary: "플랫폼 성과의 실시간 지표나 외부 캠페인 성과를 주장하는 자료는 아닙니다.",
  },
  {
    id: "ink-catalog",
    area: "Ink",
    stage: "01 / Catalog & message",
    title: "Ink catalog index",
    fileName: "README.md",
    displayPath: "INK / catalog/README.md",
    sourcePath: `${INK_CATALOG_ROOT}/README.md`,
    format: "Markdown catalog index",
    supports: "작품의 공개 메시지, 소스 런, 최종 산출물, 후속 재사용 위치를 하나의 lookup surface에 남긴 방식을 보여줍니다.",
    boundary: "원본 production run의 모든 원문을 이 폴더로 복제하지 않는 구조입니다.",
  },
  {
    id: "ink-track-board",
    area: "Ink",
    stage: "02 / Creative lock",
    title: "Track creative board",
    fileName: "track-creative-board.yaml",
    displayPath: "INK / catalog/track-creative-board.yaml",
    sourcePath: `${INK_CATALOG_ROOT}/track-creative-board.yaml`,
    format: "YAML track board",
    supports: "메시지 arc, 비주얼 보드, 생성·리뷰 경로, 수정을 포함한 track-level creative record를 확인합니다.",
    boundary: "파일이 참조하는 일부 원본 run 문서는 현재 이 워크스페이스에 남아 있지 않아 catalog pointer로만 확인됩니다.",
  },
  {
    id: "ink-output-registry",
    area: "Ink",
    stage: "03-06 / Production register",
    title: "Output registry",
    fileName: "output-registry.yaml",
    displayPath: "INK / catalog/output-registry.yaml",
    sourcePath: `${INK_CATALOG_ROOT}/output-registry.yaml`,
    format: "YAML output registry",
    supports: "키프레임·애니매틱·리뷰 sheet·편집 recipe·final master·social package로 이어진 파일 계보를 확인합니다.",
    boundary: "registry의 경로가 곧 현재 파일의 존재를 보장하지는 않습니다. 이 화면에서는 실제로 남아 있는 catalog record 자체를 증거로 둡니다.",
  },
  {
    id: "ink-look-lock",
    area: "Ink",
    stage: "02 / Creative lock",
    title: "Album look lock",
    fileName: "visual-boards/album-look-lock-v1/README.md",
    displayPath: "INK / visual-boards/album-look-lock-v1/README.md",
    sourcePath: `${INK_CATALOG_ROOT}/visual-boards/album-look-lock-v1/README.md`,
    format: "Markdown visual lock",
    supports: "작품 전반의 시각 언어를 어떻게 하나의 선택 기준으로 묶었는지 확인합니다.",
    boundary: "브랜드의 상업 가이드라인을 대체하거나 외부 브랜드 프로젝트였다는 주장은 하지 않습니다.",
  },
  {
    id: "ink-object-lock",
    area: "Ink",
    stage: "03 / Direction & coverage",
    title: "Object system lock",
    fileName: "visual-boards/object-system-lock-v1/README.md",
    displayPath: "INK / visual-boards/object-system-lock-v1/README.md",
    sourcePath: `${INK_CATALOG_ROOT}/visual-boards/object-system-lock-v1/README.md`,
    format: "Markdown object system",
    supports: "오브젝트가 장면 사이에서 어떤 의미와 연결 역할을 유지하는지 보여줍니다.",
    boundary: "공간·리테일 설치를 완성한 사례로 해석하지 않습니다.",
  },
  {
    id: "ink-solo-reference",
    area: "Ink",
    stage: "04 / Keyframe gate",
    title: "Solo section reference",
    fileName: "visual-boards/solo-section-reference-v1/README.md",
    displayPath: "INK / visual-boards/solo-section-reference-v1/README.md",
    sourcePath: `${INK_CATALOG_ROOT}/visual-boards/solo-section-reference-v1/README.md`,
    format: "Markdown reference board",
    supports: "레퍼런스를 장면 기능과 선택 기준으로 전환한 구조를 확인합니다.",
    boundary: "레퍼런스를 그대로 재현한 결과가 아니라 방향 탐색과 선별의 기록입니다.",
  },
  {
    id: "ink-social-kit",
    area: "Ink",
    stage: "06 / Package & archive",
    title: "Social kit",
    fileName: "social-kit/README.md",
    displayPath: "INK / catalog/social-kit/README.md",
    sourcePath: `${INK_CATALOG_ROOT}/social-kit/README.md`,
    format: "Markdown reuse kit",
    supports: "한 편의 영상이 섹션 클립·카피·메타데이터·게시 계획으로 확장되는 재사용 구조를 확인합니다.",
    boundary: "게시 성과의 실시간 분석이나 자동 게시의 성공을 증명하는 문서는 아닙니다.",
  },
  {
    id: "ink-asset-log",
    area: "Ink",
    stage: "06 / Package & archive",
    title: "Asset optimization log",
    fileName: "asset-optimization-log.md",
    displayPath: "INK / catalog/asset-optimization-log.md",
    sourcePath: `${INK_CATALOG_ROOT}/asset-optimization-log.md`,
    format: "Markdown delivery log",
    supports: "웹 공개용 파생 자산과 원본·QC 증거를 분리해 보관한 파일 관리 판단을 확인합니다.",
    boundary: "원본 영상과 QC를 삭제해도 된다는 의미가 아니라 공개용 파생본과 production source를 분리한 기록입니다.",
  },
  {
    id: "workbench-contract",
    area: "Workbench",
    stage: "Across / Decision surface",
    title: "Product contract",
    fileName: "docs/01-product-contract.md",
    displayPath: "WORKBENCH / docs/01-product-contract.md",
    sourcePath: `${WORKBENCH_ROOT}/docs/01-product-contract.md`,
    format: "Markdown product contract",
    supports: "텍스트 계획, 레퍼런스, 후보, sequence rail, 명시적 pass·hold·reject를 한 작업 표면에서 다루려는 범위를 확인합니다.",
    boundary: "실제 Loom run을 이 도구가 이미 승인·완료했다는 증거가 아닙니다.",
  },
  {
    id: "workbench-runtime-evidence",
    area: "Workbench",
    stage: "Across / Runtime verification",
    title: "Implemented checkpoint and runtime evidence",
    fileName: "docs/08-implemented-checkpoint-and-runtime-evidence.md",
    displayPath: "WORKBENCH / docs/08-implemented-checkpoint-and-runtime-evidence.md",
    sourcePath: `${WORKBENCH_ROOT}/docs/08-implemented-checkpoint-and-runtime-evidence.md`,
    format: "Markdown verification record",
    supports: "로컬 네이티브 실행, 테스트, 모델 turn, 상태 복구 등 개발 checkpoint의 실제 검증 범위를 확인합니다.",
    boundary: "이 문서가 명시하듯 real-song production acceptance나 최종 창작 승인 기록은 아닙니다.",
  },
  {
    id: "workbench-handoff-schema",
    area: "Workbench",
    stage: "Across / Handoff contract",
    title: "Front planning handoff schema",
    fileName: "contracts/front-planning-handoff.schema.json",
    displayPath: "WORKBENCH / contracts/front-planning-handoff.schema.json",
    sourcePath: `${WORKBENCH_ROOT}/contracts/front-planning-handoff.schema.json`,
    format: "JSON schema",
    supports: "계획 결과가 다음 production stage로 넘어갈 때 필요한 구조와 책임 경계를 확인합니다.",
    boundary: "스키마는 실행 결과가 아니라 기록 형식과 handoff 조건입니다.",
  },
  {
    id: "workbench-orchestrator",
    area: "Workbench",
    stage: "Across / Local harness code",
    title: "Workbench local harness",
    fileName: "tools/workbench.py",
    displayPath: "WORKBENCH / tools/workbench.py",
    sourcePath: `${WORKBENCH_ROOT}/tools/workbench.py`,
    format: "Python implementation",
    supports: "artifact validation, state, selection gate, context pack을 다루는 로컬 하네스 구현의 전문을 확인합니다.",
    boundary: "환경 키 이름을 검사하거나 차단할 수 있지만, 비밀값 자체는 이 파일이나 이 화면에 포함되지 않습니다.",
  },
  {
    id: "workbench-native-shell",
    area: "Workbench",
    stage: "Across / Native surface",
    title: "Native AppKit shell",
    fileName: "native-objc/Sources/main.m",
    displayPath: "WORKBENCH / native-objc/Sources/main.m",
    sourcePath: `${WORKBENCH_ROOT}/native-objc/Sources/main.m`,
    format: "Objective-C implementation",
    supports: "로컬 네이티브 화면, 후보 intake, sequence surface, 안전한 실행 경계를 구현한 코드 전문을 확인합니다.",
    boundary: "보안상 민감한 환경값을 읽거나 출력하지 않도록 막는 코드도 포함되며, 실제 credential 값은 없습니다.",
  },
  {
    id: "workbench-final-closeout",
    area: "Workbench",
    stage: "Across / Scope check",
    title: "Final token UX closeout",
    fileName: "docs/10-final-token-ux-closeout-2026-07-12.md",
    displayPath: "WORKBENCH / docs/10-final-token-ux-closeout-2026-07-12.md",
    sourcePath: `${WORKBENCH_ROOT}/docs/10-final-token-ux-closeout-2026-07-12.md`,
    format: "Markdown scope record",
    supports: "실제 demo와 UI closeout이 어디까지 완료되었는지를 확인합니다.",
    boundary: "demo 화면을 실제 콘텐츠 제작 승인 결과로 오해하지 않기 위한 상태 기록입니다.",
  },
  {
    id: "aheya-contract",
    area: "AHEYA",
    stage: "Service / Trust record",
    title: "EVM funding registry record",
    fileName: "AheyaEvmFundingRegistryRecord.sol",
    displayPath: "AHEYA / contracts/AheyaEvmFundingRegistryRecord.sol",
    sourcePath: `${AHEYA_ROOT}/aheya/contracts/AheyaEvmFundingRegistryRecord.sol`,
    format: "Solidity contract",
    supports: "AHEYA에서 제품·신뢰 기록을 개발 수준까지 탐구한 근거로, funding registry contract의 실제 소스코드를 확인합니다.",
    boundary: "블록체인 개발 직무 경력이나 운영 중인 온체인 서비스 성과로 포장하지 않습니다.",
  },
  {
    id: "aheya-yui-flow",
    area: "AHEYA",
    stage: "Service / Execute",
    title: "OpenClaw Yui flow",
    fileName: "flow.ts",
    displayPath: "AHEYA / yui_aheya/flow.ts",
    sourcePath: `${AHEYA_ROOT}/agent-packs/23-openclaw-yui-ab/runtime/virtuals-protocol-acp/src/seller/lib/yui_aheya/flow.ts`,
    format: "TypeScript implementation",
    supports: "candidate snapshot, plan, stage execution, strict review, canonical record로 이어지는 구현 흐름을 확인합니다.",
    boundary: "보존된 한 건의 실제 agent 거래 결과나 시장 성과가 아니라, 실행·기록 구조의 구현 근거입니다.",
  },
  {
    id: "aheya-yui-review",
    area: "AHEYA",
    stage: "Service / Review",
    title: "Strict review",
    fileName: "review.ts",
    displayPath: "AHEYA / yui_aheya/review.ts",
    sourcePath: `${AHEYA_ROOT}/agent-packs/23-openclaw-yui-ab/runtime/virtuals-protocol-acp/src/seller/lib/yui_aheya/review.ts`,
    format: "TypeScript implementation",
    supports: "요건·품질·제약·실행 안정성을 분리해 pass, concern, fail과 verdict로 남기는 검토 로직을 확인합니다.",
    boundary: "코드에 있는 평가 기준이 실제 시장에서 유효하다는 성과 주장은 아닙니다.",
  },
  {
    id: "aheya-yui-lane-rules",
    area: "AHEYA",
    stage: "Service / Operating boundary",
    title: "Yui AB lane rules",
    fileName: "AGENTS.md",
    displayPath: "AHEYA / workspace-yui/AGENTS.md",
    sourcePath: `${AHEYA_ROOT}/agent-packs/23-openclaw-yui-ab/runtime/workspace-yui/AGENTS.md`,
    format: "Markdown operating rule",
    supports: "delivery, canonical 기록, strict evaluation, 로그 최소화의 책임 경계를 확인합니다.",
    boundary: "문서 안에서도 raw key, bearer token, 전체 payload, 전체 deliverable을 기록하지 않도록 제한합니다.",
  },
  {
    id: "aheya-openclaw-template",
    area: "AHEYA",
    stage: "Service / Post-work record",
    title: "Trust OpenClaw skill template",
    fileName: "openclaw-skill-template.md",
    displayPath: "AHEYA / public-history/docs/trust/openclaw-skill-template.md",
    sourcePath: `${AHEYA_ROOT}/aheya-public-history/docs/trust/openclaw-skill-template.md`,
    format: "Markdown skill template",
    supports: "외부 작업 후 Trust record를 남길 때 필요한 review axes, verdict, evidence bundle을 확인합니다.",
    boundary: "public contract only template이며 private orchestration이나 credential 값을 포함하지 않습니다.",
  },
  {
    id: "aheya-feature-signal",
    area: "AHEYA",
    stage: "Service / Learn",
    title: "Feature signal sheet",
    fileName: "10-strategy-feature-signal-sheet-v1.md",
    displayPath: "AHEYA / gpt/internal-active/10-strategy-feature-signal-sheet-v1.md",
    sourcePath: `${AHEYA_ROOT}/gpt/internal-active/10-strategy-feature-signal-sheet-v1.md`,
    format: "Markdown operating template",
    supports: "선정 이유, 반응, 재사용, 회상, 후속 행동을 어떤 구조로 남기려 했는지 확인합니다.",
    boundary: "현재는 working draft template이며, 채워진 실제 운영 결과로 주장하지 않습니다.",
  },
  {
    id: "aheya-daily-brief",
    area: "AHEYA",
    stage: "Service / Operate",
    title: "Daily marketing brief automation",
    fileName: "AHEYA_DAILY_MARKETING_BRIEF_AUTOMATION.md",
    displayPath: "AHEYA / AHEYA_DAILY_MARKETING_BRIEF_AUTOMATION.md",
    sourcePath: `${AHEYA_ROOT}/AHEYA_DAILY_MARKETING_BRIEF_AUTOMATION.md`,
    format: "Markdown automation specification",
    supports: "매일 읽을 맥락, output shape, 우선순위, guardrail을 포함해 반복 운영을 어떻게 자동화하려 했는지 확인합니다.",
    boundary: "실제 scheduler 실행 로그나 반복 운영 성과는 이 문서만으로 주장하지 않습니다.",
  },
  {
    id: "aheya-evidence-ledger",
    area: "AHEYA",
    stage: "Service / Evidence boundary",
    title: "Redacted product evidence ledger",
    fileName: "x-evidence-ledger.md",
    displayPath: "AHEYA / portfolio/aheya-product-gtm/x-evidence-ledger.md",
    sourcePath: `${AHEYA_ROOT}/portfolio/aheya-product-gtm/x-evidence-ledger.md`,
    format: "Markdown redacted aggregate",
    supports: "계정·원문·개별 URL을 제외한 product evidence 집계와 공개 범위를 확인합니다.",
    boundary: "2026.05 시점의 redacted aggregate이며, 현재 실시간 성과나 개인 데이터 원문이 아닙니다.",
  },
];

export const internalHarnessStages = [
  {
    index: "01",
    title: "무엇을 만들지, 무엇을 만들지 않을지 먼저 고정한다",
    detail: "메시지·레퍼런스·오디오·장면의 역할을 생성 전에 읽고, 자동화가 넘지 않을 창의 판단 경계를 둡니다.",
    pulso: ["pulso-readiness", "pulso-nucleus", "pulso-song-lock"],
    ink: ["ink-catalog", "ink-track-board", "ink-look-lock"],
  },
  {
    index: "02",
    title: "방향을 화면 단위의 coverage로 번역한다",
    detail: "세계, 인물, 오브젝트, 카메라, 컷 연결을 후보 생산의 기준으로 옮깁니다.",
    pulso: ["pulso-direction-map", "pulso-visual-board", "pulso-generation-map"],
    ink: ["ink-track-board", "ink-object-lock", "ink-solo-reference"],
  },
  {
    index: "03",
    title: "생성 전에 keyframe과 실행 단위를 검토한다",
    detail: "스토리보드와 prompt packet을 분리해, 프롬프트가 새로운 창의 판단을 덮어쓰지 않게 합니다.",
    pulso: ["pulso-storyboard", "pulso-prompt-packets"],
    ink: ["ink-track-board", "ink-output-registry"],
  },
  {
    index: "04",
    title: "후보를 통과·보류·수정으로 분리하고 편집 recipe로 남긴다",
    detail: "결과물의 양보다 연결, 연속성, 타이밍, 다음 수정 판단을 중심으로 검토합니다.",
    pulso: ["pulso-review", "pulso-edit-map"],
    ink: ["ink-output-registry", "ink-asset-log"],
  },
  {
    index: "05",
    title: "완성본을 다음 공개·재사용·판단으로 넘긴다",
    detail: "최종 산출물만 남기지 않고 package, social reuse, evidence boundary를 함께 남깁니다.",
    pulso: ["pulso-package"],
    ink: ["ink-output-registry", "ink-social-kit", "ink-asset-log"],
  },
] as const;

export const internalEvidenceAreas: EvidenceArea[] = ["Pulso", "Ink", "Workbench", "AHEYA"];

export function getInternalEvidenceArtifact(id: string) {
  return internalEvidenceArtifacts.find((artifact) => artifact.id === id);
}

export function getInternalEvidenceArtifacts(ids: readonly string[]) {
  return ids
    .map((id) => getInternalEvidenceArtifact(id))
    .filter((artifact): artifact is InternalEvidenceArtifact => Boolean(artifact));
}

export async function readInternalEvidenceArtifact(artifact: InternalEvidenceArtifact) {
  const [content, sourceStat] = await Promise.all([readFile(artifact.sourcePath, "utf8"), stat(artifact.sourcePath)]);

  return {
    content: content.replaceAll("\u0000", ""),
    lineCount: content.split("\n").length,
    byteCount: sourceStat.size,
  };
}
